//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Admin.HistoryService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HistoryService.IHistoryService")]
    public interface IHistoryService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHistoryService/GetList", ReplyAction="http://tempuri.org/IHistoryService/GetListResponse")]
        Wow.Tv.Middle.Model.Db49.wowtv.History.HistoryModel<Wow.Tv.Middle.Model.Db49.wowtv.History.HIS_CTGR> GetList(Wow.Tv.Middle.Model.Db49.wowtv.History.HistoryCondition codition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHistoryService/GetList", ReplyAction="http://tempuri.org/IHistoryService/GetListResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.History.HistoryModel<Wow.Tv.Middle.Model.Db49.wowtv.History.HIS_CTGR>> GetListAsync(Wow.Tv.Middle.Model.Db49.wowtv.History.HistoryCondition codition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHistoryService/GetDetail", ReplyAction="http://tempuri.org/IHistoryService/GetDetailResponse")]
        Wow.Tv.Middle.Model.Db49.wowtv.History.HistoryDetail GetDetail(int seq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHistoryService/GetDetail", ReplyAction="http://tempuri.org/IHistoryService/GetDetailResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.History.HistoryDetail> GetDetailAsync(int seq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHistoryService/Save", ReplyAction="http://tempuri.org/IHistoryService/SaveResponse")]
        int Save(Wow.Tv.Middle.Model.Db49.wowtv.NTB_HIS_MNG model, Wow.Tv.Middle.Model.Common.LoginUser loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHistoryService/Save", ReplyAction="http://tempuri.org/IHistoryService/SaveResponse")]
        System.Threading.Tasks.Task<int> SaveAsync(Wow.Tv.Middle.Model.Db49.wowtv.NTB_HIS_MNG model, Wow.Tv.Middle.Model.Common.LoginUser loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHistoryService/Delete", ReplyAction="http://tempuri.org/IHistoryService/DeleteResponse")]
        void Delete(int[] seqList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHistoryService/Delete", ReplyAction="http://tempuri.org/IHistoryService/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(int[] seqList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHistoryService/SearchHistory", ReplyAction="http://tempuri.org/IHistoryService/SearchHistoryResponse")]
        Wow.Tv.Middle.Model.Db49.wowtv.History.DtlCTGRHistory[] SearchHistory(string SearchYear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHistoryService/SearchHistory", ReplyAction="http://tempuri.org/IHistoryService/SearchHistoryResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.History.DtlCTGRHistory[]> SearchHistoryAsync(string SearchYear);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHistoryServiceChannel : Wow.Tv.Admin.HistoryService.IHistoryService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HistoryServiceClient : System.ServiceModel.ClientBase<Wow.Tv.Admin.HistoryService.IHistoryService>, Wow.Tv.Admin.HistoryService.IHistoryService {
        
        public HistoryServiceClient() {
        }
        
        public HistoryServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HistoryServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HistoryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HistoryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Wow.Tv.Middle.Model.Db49.wowtv.History.HistoryModel<Wow.Tv.Middle.Model.Db49.wowtv.History.HIS_CTGR> GetList(Wow.Tv.Middle.Model.Db49.wowtv.History.HistoryCondition codition) {
            return base.Channel.GetList(codition);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.History.HistoryModel<Wow.Tv.Middle.Model.Db49.wowtv.History.HIS_CTGR>> GetListAsync(Wow.Tv.Middle.Model.Db49.wowtv.History.HistoryCondition codition) {
            return base.Channel.GetListAsync(codition);
        }
        
        public Wow.Tv.Middle.Model.Db49.wowtv.History.HistoryDetail GetDetail(int seq) {
            return base.Channel.GetDetail(seq);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.History.HistoryDetail> GetDetailAsync(int seq) {
            return base.Channel.GetDetailAsync(seq);
        }
        
        public int Save(Wow.Tv.Middle.Model.Db49.wowtv.NTB_HIS_MNG model, Wow.Tv.Middle.Model.Common.LoginUser loginUser) {
            return base.Channel.Save(model, loginUser);
        }
        
        public System.Threading.Tasks.Task<int> SaveAsync(Wow.Tv.Middle.Model.Db49.wowtv.NTB_HIS_MNG model, Wow.Tv.Middle.Model.Common.LoginUser loginUser) {
            return base.Channel.SaveAsync(model, loginUser);
        }
        
        public void Delete(int[] seqList) {
            base.Channel.Delete(seqList);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(int[] seqList) {
            return base.Channel.DeleteAsync(seqList);
        }
        
        public Wow.Tv.Middle.Model.Db49.wowtv.History.DtlCTGRHistory[] SearchHistory(string SearchYear) {
            return base.Channel.SearchHistory(SearchYear);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.History.DtlCTGRHistory[]> SearchHistoryAsync(string SearchYear) {
            return base.Channel.SearchHistoryAsync(SearchYear);
        }
    }
}
