//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Admin.StockSituationService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StockSituationService.IStockSituationService")]
    public interface IStockSituationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockSituationService/GetList", ReplyAction="http://tempuri.org/IStockSituationService/GetListResponse")]
        Wow.Tv.Middle.Model.Db49.wownet.StockSituation.StockModel<Wow.Tv.Middle.Model.Db49.wownet.TAB_STOCK_SITUATION> GetList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockSituationService/GetList", ReplyAction="http://tempuri.org/IStockSituationService/GetListResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wownet.StockSituation.StockModel<Wow.Tv.Middle.Model.Db49.wownet.TAB_STOCK_SITUATION>> GetListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockSituationService/Save", ReplyAction="http://tempuri.org/IStockSituationService/SaveResponse")]
        int Save(Wow.Tv.Middle.Model.Db49.wownet.TAB_STOCK_SITUATION model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockSituationService/Save", ReplyAction="http://tempuri.org/IStockSituationService/SaveResponse")]
        System.Threading.Tasks.Task<int> SaveAsync(Wow.Tv.Middle.Model.Db49.wownet.TAB_STOCK_SITUATION model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockSituationService/Delete", ReplyAction="http://tempuri.org/IStockSituationService/DeleteResponse")]
        void Delete(int seq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockSituationService/Delete", ReplyAction="http://tempuri.org/IStockSituationService/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(int seq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockSituationService/UpdateOrder", ReplyAction="http://tempuri.org/IStockSituationService/UpdateOrderResponse")]
        void UpdateOrder(int seq, bool isUp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockSituationService/UpdateOrder", ReplyAction="http://tempuri.org/IStockSituationService/UpdateOrderResponse")]
        System.Threading.Tasks.Task UpdateOrderAsync(int seq, bool isUp);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStockSituationServiceChannel : Wow.Tv.Admin.StockSituationService.IStockSituationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StockSituationServiceClient : System.ServiceModel.ClientBase<Wow.Tv.Admin.StockSituationService.IStockSituationService>, Wow.Tv.Admin.StockSituationService.IStockSituationService {
        
        public StockSituationServiceClient() {
        }
        
        public StockSituationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StockSituationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StockSituationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StockSituationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Wow.Tv.Middle.Model.Db49.wownet.StockSituation.StockModel<Wow.Tv.Middle.Model.Db49.wownet.TAB_STOCK_SITUATION> GetList() {
            return base.Channel.GetList();
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wownet.StockSituation.StockModel<Wow.Tv.Middle.Model.Db49.wownet.TAB_STOCK_SITUATION>> GetListAsync() {
            return base.Channel.GetListAsync();
        }
        
        public int Save(Wow.Tv.Middle.Model.Db49.wownet.TAB_STOCK_SITUATION model) {
            return base.Channel.Save(model);
        }
        
        public System.Threading.Tasks.Task<int> SaveAsync(Wow.Tv.Middle.Model.Db49.wownet.TAB_STOCK_SITUATION model) {
            return base.Channel.SaveAsync(model);
        }
        
        public void Delete(int seq) {
            base.Channel.Delete(seq);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(int seq) {
            return base.Channel.DeleteAsync(seq);
        }
        
        public void UpdateOrder(int seq, bool isUp) {
            base.Channel.UpdateOrder(seq, isUp);
        }
        
        public System.Threading.Tasks.Task UpdateOrderAsync(int seq, bool isUp) {
            return base.Channel.UpdateOrderAsync(seq, isUp);
        }
    }
}
