//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Admin.StockResultService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StockResultService.IStockResultService")]
    public interface IStockResultService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockResultService/GetList", ReplyAction="http://tempuri.org/IStockResultService/GetListResponse")]
        Wow.Tv.Middle.Model.Db49.wownet.StockResult.StockResultModel<Wow.Tv.Middle.Model.Db49.wownet.TAB_STOCK_RESULT> GetList(Wow.Tv.Middle.Model.Db49.wownet.StockResult.StockResultCondition condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockResultService/GetList", ReplyAction="http://tempuri.org/IStockResultService/GetListResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wownet.StockResult.StockResultModel<Wow.Tv.Middle.Model.Db49.wownet.TAB_STOCK_RESULT>> GetListAsync(Wow.Tv.Middle.Model.Db49.wownet.StockResult.StockResultCondition condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockResultService/Save", ReplyAction="http://tempuri.org/IStockResultService/SaveResponse")]
        int Save(Wow.Tv.Middle.Model.Db49.wownet.StockResult.StockResultDetail data, Wow.Tv.Middle.Model.Common.LoginUser loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockResultService/Save", ReplyAction="http://tempuri.org/IStockResultService/SaveResponse")]
        System.Threading.Tasks.Task<int> SaveAsync(Wow.Tv.Middle.Model.Db49.wownet.StockResult.StockResultDetail data, Wow.Tv.Middle.Model.Common.LoginUser loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockResultService/GetData", ReplyAction="http://tempuri.org/IStockResultService/GetDataResponse")]
        Wow.Tv.Middle.Model.Db49.wownet.StockResult.StockResultDetail GetData(int seq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockResultService/GetData", ReplyAction="http://tempuri.org/IStockResultService/GetDataResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wownet.StockResult.StockResultDetail> GetDataAsync(int seq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockResultService/Delete", ReplyAction="http://tempuri.org/IStockResultService/DeleteResponse")]
        void Delete(int[] deleteList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockResultService/Delete", ReplyAction="http://tempuri.org/IStockResultService/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(int[] deleteList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockResultService/GetJoinList", ReplyAction="http://tempuri.org/IStockResultService/GetJoinListResponse")]
        Wow.Tv.Middle.Model.Db49.wownet.StockResult.StockResultModel<Wow.Tv.Middle.Model.Db49.wownet.StockResult.JOIN_STOCK_CONNECT> GetJoinList(Wow.Tv.Middle.Model.Db49.wownet.StockResult.StockResultCondition condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockResultService/GetJoinList", ReplyAction="http://tempuri.org/IStockResultService/GetJoinListResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wownet.StockResult.StockResultModel<Wow.Tv.Middle.Model.Db49.wownet.StockResult.JOIN_STOCK_CONNECT>> GetJoinListAsync(Wow.Tv.Middle.Model.Db49.wownet.StockResult.StockResultCondition condition);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStockResultServiceChannel : Wow.Tv.Admin.StockResultService.IStockResultService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StockResultServiceClient : System.ServiceModel.ClientBase<Wow.Tv.Admin.StockResultService.IStockResultService>, Wow.Tv.Admin.StockResultService.IStockResultService {
        
        public StockResultServiceClient() {
        }
        
        public StockResultServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StockResultServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StockResultServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StockResultServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Wow.Tv.Middle.Model.Db49.wownet.StockResult.StockResultModel<Wow.Tv.Middle.Model.Db49.wownet.TAB_STOCK_RESULT> GetList(Wow.Tv.Middle.Model.Db49.wownet.StockResult.StockResultCondition condition) {
            return base.Channel.GetList(condition);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wownet.StockResult.StockResultModel<Wow.Tv.Middle.Model.Db49.wownet.TAB_STOCK_RESULT>> GetListAsync(Wow.Tv.Middle.Model.Db49.wownet.StockResult.StockResultCondition condition) {
            return base.Channel.GetListAsync(condition);
        }
        
        public int Save(Wow.Tv.Middle.Model.Db49.wownet.StockResult.StockResultDetail data, Wow.Tv.Middle.Model.Common.LoginUser loginUser) {
            return base.Channel.Save(data, loginUser);
        }
        
        public System.Threading.Tasks.Task<int> SaveAsync(Wow.Tv.Middle.Model.Db49.wownet.StockResult.StockResultDetail data, Wow.Tv.Middle.Model.Common.LoginUser loginUser) {
            return base.Channel.SaveAsync(data, loginUser);
        }
        
        public Wow.Tv.Middle.Model.Db49.wownet.StockResult.StockResultDetail GetData(int seq) {
            return base.Channel.GetData(seq);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wownet.StockResult.StockResultDetail> GetDataAsync(int seq) {
            return base.Channel.GetDataAsync(seq);
        }
        
        public void Delete(int[] deleteList) {
            base.Channel.Delete(deleteList);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(int[] deleteList) {
            return base.Channel.DeleteAsync(deleteList);
        }
        
        public Wow.Tv.Middle.Model.Db49.wownet.StockResult.StockResultModel<Wow.Tv.Middle.Model.Db49.wownet.StockResult.JOIN_STOCK_CONNECT> GetJoinList(Wow.Tv.Middle.Model.Db49.wownet.StockResult.StockResultCondition condition) {
            return base.Channel.GetJoinList(condition);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wownet.StockResult.StockResultModel<Wow.Tv.Middle.Model.Db49.wownet.StockResult.JOIN_STOCK_CONNECT>> GetJoinListAsync(Wow.Tv.Middle.Model.Db49.wownet.StockResult.StockResultCondition condition) {
            return base.Channel.GetJoinListAsync(condition);
        }
    }
}
