//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Admin.BusinessManageService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BusinessManageService.IBusinessManageService")]
    public interface IBusinessManageService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessManageService/SearchList", ReplyAction="http://tempuri.org/IBusinessManageService/SearchListResponse")]
        Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.BusinessManage.BOARD_CONT_MENU> SearchList(Wow.Tv.Middle.Model.Db49.wowtv.BusinessManage.BusinessCondition condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessManageService/SearchList", ReplyAction="http://tempuri.org/IBusinessManageService/SearchListResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.BusinessManage.BOARD_CONT_MENU>> SearchListAsync(Wow.Tv.Middle.Model.Db49.wowtv.BusinessManage.BusinessCondition condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessManageService/GetDetail", ReplyAction="http://tempuri.org/IBusinessManageService/GetDetailResponse")]
        Wow.Tv.Middle.Model.Db49.wowtv.BusinessManage.BOARD_CONT_MENU GetDetail(int seq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessManageService/GetDetail", ReplyAction="http://tempuri.org/IBusinessManageService/GetDetailResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.BusinessManage.BOARD_CONT_MENU> GetDetailAsync(int seq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessManageService/Save", ReplyAction="http://tempuri.org/IBusinessManageService/SaveResponse")]
        int Save(Wow.Tv.Middle.Model.Db49.wowtv.NTB_BOARD_CONTENT model, Wow.Tv.Middle.Model.Common.LoginUser loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessManageService/Save", ReplyAction="http://tempuri.org/IBusinessManageService/SaveResponse")]
        System.Threading.Tasks.Task<int> SaveAsync(Wow.Tv.Middle.Model.Db49.wowtv.NTB_BOARD_CONTENT model, Wow.Tv.Middle.Model.Common.LoginUser loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessManageService/Delete", ReplyAction="http://tempuri.org/IBusinessManageService/DeleteResponse")]
        void Delete(int[] seqList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessManageService/Delete", ReplyAction="http://tempuri.org/IBusinessManageService/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(int[] seqList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessManageService/SearchData", ReplyAction="http://tempuri.org/IBusinessManageService/SearchDataResponse")]
        Wow.Tv.Middle.Model.Db49.wowtv.NTB_BOARD_CONTENT SearchData(int menuSeq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessManageService/SearchData", ReplyAction="http://tempuri.org/IBusinessManageService/SearchDataResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.NTB_BOARD_CONTENT> SearchDataAsync(int menuSeq);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBusinessManageServiceChannel : Wow.Tv.Admin.BusinessManageService.IBusinessManageService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BusinessManageServiceClient : System.ServiceModel.ClientBase<Wow.Tv.Admin.BusinessManageService.IBusinessManageService>, Wow.Tv.Admin.BusinessManageService.IBusinessManageService {
        
        public BusinessManageServiceClient() {
        }
        
        public BusinessManageServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BusinessManageServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BusinessManageServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BusinessManageServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.BusinessManage.BOARD_CONT_MENU> SearchList(Wow.Tv.Middle.Model.Db49.wowtv.BusinessManage.BusinessCondition condition) {
            return base.Channel.SearchList(condition);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.BusinessManage.BOARD_CONT_MENU>> SearchListAsync(Wow.Tv.Middle.Model.Db49.wowtv.BusinessManage.BusinessCondition condition) {
            return base.Channel.SearchListAsync(condition);
        }
        
        public Wow.Tv.Middle.Model.Db49.wowtv.BusinessManage.BOARD_CONT_MENU GetDetail(int seq) {
            return base.Channel.GetDetail(seq);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.BusinessManage.BOARD_CONT_MENU> GetDetailAsync(int seq) {
            return base.Channel.GetDetailAsync(seq);
        }
        
        public int Save(Wow.Tv.Middle.Model.Db49.wowtv.NTB_BOARD_CONTENT model, Wow.Tv.Middle.Model.Common.LoginUser loginUser) {
            return base.Channel.Save(model, loginUser);
        }
        
        public System.Threading.Tasks.Task<int> SaveAsync(Wow.Tv.Middle.Model.Db49.wowtv.NTB_BOARD_CONTENT model, Wow.Tv.Middle.Model.Common.LoginUser loginUser) {
            return base.Channel.SaveAsync(model, loginUser);
        }
        
        public void Delete(int[] seqList) {
            base.Channel.Delete(seqList);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(int[] seqList) {
            return base.Channel.DeleteAsync(seqList);
        }
        
        public Wow.Tv.Middle.Model.Db49.wowtv.NTB_BOARD_CONTENT SearchData(int menuSeq) {
            return base.Channel.SearchData(menuSeq);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.NTB_BOARD_CONTENT> SearchDataAsync(int menuSeq) {
            return base.Channel.SearchDataAsync(menuSeq);
        }
    }
}
