//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Admin.ArticleStatsService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ArticleStatsService.IArticleStatsService")]
    public interface IArticleStatsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArticleStatsService/GetArticleSearchList", ReplyAction="http://tempuri.org/IArticleStatsService/GetArticleSearchListResponse")]
        Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.Article.NUP_ARTICLE_SELECT_Result> GetArticleSearchList(Wow.Tv.Middle.Model.Db49.Article.Stats.StatsCondition condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArticleStatsService/GetArticleSearchList", ReplyAction="http://tempuri.org/IArticleStatsService/GetArticleSearchListResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.Article.NUP_ARTICLE_SELECT_Result>> GetArticleSearchListAsync(Wow.Tv.Middle.Model.Db49.Article.Stats.StatsCondition condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArticleStatsService/GetProvideSearchList", ReplyAction="http://tempuri.org/IArticleStatsService/GetProvideSearchListResponse")]
        Wow.Tv.Middle.Model.Db49.Article.NUP_ARTICLE_PROVIDE_SELECT_Result[] GetProvideSearchList(Wow.Tv.Middle.Model.Db49.Article.Stats.StatsCondition condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArticleStatsService/GetProvideSearchList", ReplyAction="http://tempuri.org/IArticleStatsService/GetProvideSearchListResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.Article.NUP_ARTICLE_PROVIDE_SELECT_Result[]> GetProvideSearchListAsync(Wow.Tv.Middle.Model.Db49.Article.Stats.StatsCondition condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArticleStatsService/GetFreelancerTrafficList", ReplyAction="http://tempuri.org/IArticleStatsService/GetFreelancerTrafficListResponse")]
        Wow.Tv.Middle.Model.Db49.Article.NUP_FREELANCER_TRAFFIC_SELECT_Result[] GetFreelancerTrafficList(Wow.Tv.Middle.Model.Db49.Article.Stats.StatsCondition condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArticleStatsService/GetFreelancerTrafficList", ReplyAction="http://tempuri.org/IArticleStatsService/GetFreelancerTrafficListResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.Article.NUP_FREELANCER_TRAFFIC_SELECT_Result[]> GetFreelancerTrafficListAsync(Wow.Tv.Middle.Model.Db49.Article.Stats.StatsCondition condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArticleStatsService/GetFreelancerArticleRankList", ReplyAction="http://tempuri.org/IArticleStatsService/GetFreelancerArticleRankListResponse")]
        Wow.Tv.Middle.Model.Db49.Article.NUP_FREELANCER_ARTICLE_RANK_SELECT_Result[] GetFreelancerArticleRankList(Wow.Tv.Middle.Model.Db49.Article.Stats.StatsCondition condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArticleStatsService/GetFreelancerArticleRankList", ReplyAction="http://tempuri.org/IArticleStatsService/GetFreelancerArticleRankListResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.Article.NUP_FREELANCER_ARTICLE_RANK_SELECT_Result[]> GetFreelancerArticleRankListAsync(Wow.Tv.Middle.Model.Db49.Article.Stats.StatsCondition condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArticleStatsService/GetPresentMember", ReplyAction="http://tempuri.org/IArticleStatsService/GetPresentMemberResponse")]
        Wow.Tv.Middle.Model.Db89.wowbill.PresentMember GetPresentMember(System.DateTime startDateTime, System.DateTime endDateTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArticleStatsService/GetPresentMember", ReplyAction="http://tempuri.org/IArticleStatsService/GetPresentMemberResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.PresentMember> GetPresentMemberAsync(System.DateTime startDateTime, System.DateTime endDateTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArticleStatsService/SaveTrafficRank", ReplyAction="http://tempuri.org/IArticleStatsService/SaveTrafficRankResponse")]
        void SaveTrafficRank(int rank, Wow.Tv.Middle.Model.Common.LoginUser loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArticleStatsService/SaveTrafficRank", ReplyAction="http://tempuri.org/IArticleStatsService/SaveTrafficRankResponse")]
        System.Threading.Tasks.Task SaveTrafficRankAsync(int rank, Wow.Tv.Middle.Model.Common.LoginUser loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArticleStatsService/GetArtIdbyWriter", ReplyAction="http://tempuri.org/IArticleStatsService/GetArtIdbyWriterResponse")]
        string GetArtIdbyWriter(string compCode, string artId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArticleStatsService/GetArtIdbyWriter", ReplyAction="http://tempuri.org/IArticleStatsService/GetArtIdbyWriterResponse")]
        System.Threading.Tasks.Task<string> GetArtIdbyWriterAsync(string compCode, string artId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArticleStatsService/ReportCount", ReplyAction="http://tempuri.org/IArticleStatsService/ReportCountResponse")]
        int ReportCount(System.DateTime startDateTime, System.DateTime endDateTime, string contentSeq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArticleStatsService/ReportCount", ReplyAction="http://tempuri.org/IArticleStatsService/ReportCountResponse")]
        System.Threading.Tasks.Task<int> ReportCountAsync(System.DateTime startDateTime, System.DateTime endDateTime, string contentSeq);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IArticleStatsServiceChannel : Wow.Tv.Admin.ArticleStatsService.IArticleStatsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ArticleStatsServiceClient : System.ServiceModel.ClientBase<Wow.Tv.Admin.ArticleStatsService.IArticleStatsService>, Wow.Tv.Admin.ArticleStatsService.IArticleStatsService {
        
        public ArticleStatsServiceClient() {
        }
        
        public ArticleStatsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ArticleStatsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ArticleStatsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ArticleStatsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.Article.NUP_ARTICLE_SELECT_Result> GetArticleSearchList(Wow.Tv.Middle.Model.Db49.Article.Stats.StatsCondition condition) {
            return base.Channel.GetArticleSearchList(condition);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.Article.NUP_ARTICLE_SELECT_Result>> GetArticleSearchListAsync(Wow.Tv.Middle.Model.Db49.Article.Stats.StatsCondition condition) {
            return base.Channel.GetArticleSearchListAsync(condition);
        }
        
        public Wow.Tv.Middle.Model.Db49.Article.NUP_ARTICLE_PROVIDE_SELECT_Result[] GetProvideSearchList(Wow.Tv.Middle.Model.Db49.Article.Stats.StatsCondition condition) {
            return base.Channel.GetProvideSearchList(condition);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.Article.NUP_ARTICLE_PROVIDE_SELECT_Result[]> GetProvideSearchListAsync(Wow.Tv.Middle.Model.Db49.Article.Stats.StatsCondition condition) {
            return base.Channel.GetProvideSearchListAsync(condition);
        }
        
        public Wow.Tv.Middle.Model.Db49.Article.NUP_FREELANCER_TRAFFIC_SELECT_Result[] GetFreelancerTrafficList(Wow.Tv.Middle.Model.Db49.Article.Stats.StatsCondition condition) {
            return base.Channel.GetFreelancerTrafficList(condition);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.Article.NUP_FREELANCER_TRAFFIC_SELECT_Result[]> GetFreelancerTrafficListAsync(Wow.Tv.Middle.Model.Db49.Article.Stats.StatsCondition condition) {
            return base.Channel.GetFreelancerTrafficListAsync(condition);
        }
        
        public Wow.Tv.Middle.Model.Db49.Article.NUP_FREELANCER_ARTICLE_RANK_SELECT_Result[] GetFreelancerArticleRankList(Wow.Tv.Middle.Model.Db49.Article.Stats.StatsCondition condition) {
            return base.Channel.GetFreelancerArticleRankList(condition);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.Article.NUP_FREELANCER_ARTICLE_RANK_SELECT_Result[]> GetFreelancerArticleRankListAsync(Wow.Tv.Middle.Model.Db49.Article.Stats.StatsCondition condition) {
            return base.Channel.GetFreelancerArticleRankListAsync(condition);
        }
        
        public Wow.Tv.Middle.Model.Db89.wowbill.PresentMember GetPresentMember(System.DateTime startDateTime, System.DateTime endDateTime) {
            return base.Channel.GetPresentMember(startDateTime, endDateTime);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.PresentMember> GetPresentMemberAsync(System.DateTime startDateTime, System.DateTime endDateTime) {
            return base.Channel.GetPresentMemberAsync(startDateTime, endDateTime);
        }
        
        public void SaveTrafficRank(int rank, Wow.Tv.Middle.Model.Common.LoginUser loginUser) {
            base.Channel.SaveTrafficRank(rank, loginUser);
        }
        
        public System.Threading.Tasks.Task SaveTrafficRankAsync(int rank, Wow.Tv.Middle.Model.Common.LoginUser loginUser) {
            return base.Channel.SaveTrafficRankAsync(rank, loginUser);
        }
        
        public string GetArtIdbyWriter(string compCode, string artId) {
            return base.Channel.GetArtIdbyWriter(compCode, artId);
        }
        
        public System.Threading.Tasks.Task<string> GetArtIdbyWriterAsync(string compCode, string artId) {
            return base.Channel.GetArtIdbyWriterAsync(compCode, artId);
        }
        
        public int ReportCount(System.DateTime startDateTime, System.DateTime endDateTime, string contentSeq) {
            return base.Channel.ReportCount(startDateTime, endDateTime, contentSeq);
        }
        
        public System.Threading.Tasks.Task<int> ReportCountAsync(System.DateTime startDateTime, System.DateTime endDateTime, string contentSeq) {
            return base.Channel.ReportCountAsync(startDateTime, endDateTime, contentSeq);
        }
    }
}
