//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Admin.MemberManageService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SetPasswordResult", Namespace="http://schemas.datacontract.org/2004/07/Wow.Tv.Middle.Biz.Member")]
    [System.SerializableAttribute()]
    public partial class SetPasswordResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReturnMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TempPasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MobileNo {
            get {
                return this.MobileNoField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileNoField, value) != true)) {
                    this.MobileNoField = value;
                    this.RaisePropertyChanged("MobileNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReturnMessage {
            get {
                return this.ReturnMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ReturnMessageField, value) != true)) {
                    this.ReturnMessageField = value;
                    this.RaisePropertyChanged("ReturnMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TempPassword {
            get {
                return this.TempPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.TempPasswordField, value) != true)) {
                    this.TempPasswordField = value;
                    this.RaisePropertyChanged("TempPassword");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MemberManageService.IMemberManageService")]
    public interface IMemberManageService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberManageService/MemberSearchList", ReplyAction="http://tempuri.org/IMemberManageService/MemberSearchListResponse")]
        Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db89.wowbill.MemberAdminManage.MemberManageListResult> MemberSearchList(Wow.Tv.Middle.Model.Db89.wowbill.MemberAdminManage.MemberManageCondition condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberManageService/MemberSearchList", ReplyAction="http://tempuri.org/IMemberManageService/MemberSearchListResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db89.wowbill.MemberAdminManage.MemberManageListResult>> MemberSearchListAsync(Wow.Tv.Middle.Model.Db89.wowbill.MemberAdminManage.MemberManageCondition condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberManageService/MemberInfo", ReplyAction="http://tempuri.org/IMemberManageService/MemberInfoResponse")]
        Wow.Tv.Middle.Model.Db89.wowbill.MemberAdminManage.MemberManageInfoResult MemberInfo(int userNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberManageService/MemberInfo", ReplyAction="http://tempuri.org/IMemberManageService/MemberInfoResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.MemberAdminManage.MemberManageInfoResult> MemberInfoAsync(int userNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberManageService/MemberInfoSave", ReplyAction="http://tempuri.org/IMemberManageService/MemberInfoSaveResponse")]
        Wow.Tv.Middle.Model.Db89.wowbill.MemberAdminManage.UserInfoModifyResult MemberInfoSave(Wow.Tv.Middle.Model.Db89.wowbill.MemberAdminManage.UserInfoSaveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberManageService/MemberInfoSave", ReplyAction="http://tempuri.org/IMemberManageService/MemberInfoSaveResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.MemberAdminManage.UserInfoModifyResult> MemberInfoSaveAsync(Wow.Tv.Middle.Model.Db89.wowbill.MemberAdminManage.UserInfoSaveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberManageService/MemberSecession", ReplyAction="http://tempuri.org/IMemberManageService/MemberSecessionResponse")]
        Wow.Tv.Middle.Model.Db89.wowbill.Member.MemberSecessionResult MemberSecession(int userNumber, string secessionReasonKey, string secessionReasonDescription);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberManageService/MemberSecession", ReplyAction="http://tempuri.org/IMemberManageService/MemberSecessionResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.Member.MemberSecessionResult> MemberSecessionAsync(int userNumber, string secessionReasonKey, string secessionReasonDescription);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberManageService/GetAddress", ReplyAction="http://tempuri.org/IMemberManageService/GetAddressResponse")]
        Wow.Tv.Middle.Model.Db89.wowbill.tblPost[] GetAddress(string searchKeyword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberManageService/GetAddress", ReplyAction="http://tempuri.org/IMemberManageService/GetAddressResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.tblPost[]> GetAddressAsync(string searchKeyword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberManageService/MemberInfoStatistics", ReplyAction="http://tempuri.org/IMemberManageService/MemberInfoStatisticsResponse")]
        Wow.Tv.Middle.Model.Db89.wowbill.MemberAdminManage.MemberInfoStatisticsResult MemberInfoStatistics();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberManageService/MemberInfoStatistics", ReplyAction="http://tempuri.org/IMemberManageService/MemberInfoStatisticsResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.MemberAdminManage.MemberInfoStatisticsResult> MemberInfoStatisticsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberManageService/PasswordInitialize", ReplyAction="http://tempuri.org/IMemberManageService/PasswordInitializeResponse")]
        Wow.Tv.Admin.MemberManageService.SetPasswordResult PasswordInitialize(int userNumber, string adminId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberManageService/PasswordInitialize", ReplyAction="http://tempuri.org/IMemberManageService/PasswordInitializeResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Admin.MemberManageService.SetPasswordResult> PasswordInitializeAsync(int userNumber, string adminId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberManageService/SendSms", ReplyAction="http://tempuri.org/IMemberManageService/SendSmsResponse")]
        void SendSms(string receiveNo, string callbackNo, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberManageService/SendSms", ReplyAction="http://tempuri.org/IMemberManageService/SendSmsResponse")]
        System.Threading.Tasks.Task SendSmsAsync(string receiveNo, string callbackNo, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberManageService/UserApproval", ReplyAction="http://tempuri.org/IMemberManageService/UserApprovalResponse")]
        void UserApproval(int userNumber, bool approved, string reason);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberManageService/UserApproval", ReplyAction="http://tempuri.org/IMemberManageService/UserApprovalResponse")]
        System.Threading.Tasks.Task UserApprovalAsync(int userNumber, bool approved, string reason);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberManageService/SimpleMemberList", ReplyAction="http://tempuri.org/IMemberManageService/SimpleMemberListResponse")]
        Wow.Tv.Middle.Model.Db89.wowbill.MemberAdminManage.MemberInfoSimple[] SimpleMemberList(int[] userNumberList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberManageService/SimpleMemberList", ReplyAction="http://tempuri.org/IMemberManageService/SimpleMemberListResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.MemberAdminManage.MemberInfoSimple[]> SimpleMemberListAsync(int[] userNumberList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberManageService/RestoreDormancy", ReplyAction="http://tempuri.org/IMemberManageService/RestoreDormancyResponse")]
        string RestoreDormancy(int userNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberManageService/RestoreDormancy", ReplyAction="http://tempuri.org/IMemberManageService/RestoreDormancyResponse")]
        System.Threading.Tasks.Task<string> RestoreDormancyAsync(int userNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberManageService/MemberDIDenialList", ReplyAction="http://tempuri.org/IMemberManageService/MemberDIDenialListResponse")]
        Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db89.wowbill.TblMemberDIDenialList> MemberDIDenialList(Wow.Tv.Middle.Model.Db49.wowtv.Board.IntegratedBoardCondition condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberManageService/MemberDIDenialList", ReplyAction="http://tempuri.org/IMemberManageService/MemberDIDenialListResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db89.wowbill.TblMemberDIDenialList>> MemberDIDenialListAsync(Wow.Tv.Middle.Model.Db49.wowtv.Board.IntegratedBoardCondition condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberManageService/MemberDIDenialWriteProc", ReplyAction="http://tempuri.org/IMemberManageService/MemberDIDenialWriteProcResponse")]
        void MemberDIDenialWriteProc(Wow.Tv.Middle.Model.Db89.wowbill.TblMemberDIDenialList model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberManageService/MemberDIDenialWriteProc", ReplyAction="http://tempuri.org/IMemberManageService/MemberDIDenialWriteProcResponse")]
        System.Threading.Tasks.Task MemberDIDenialWriteProcAsync(Wow.Tv.Middle.Model.Db89.wowbill.TblMemberDIDenialList model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberManageService/MemberDIDenialView", ReplyAction="http://tempuri.org/IMemberManageService/MemberDIDenialViewResponse")]
        Wow.Tv.Middle.Model.Db89.wowbill.TblMemberDIDenialList MemberDIDenialView(int seq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberManageService/MemberDIDenialView", ReplyAction="http://tempuri.org/IMemberManageService/MemberDIDenialViewResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.TblMemberDIDenialList> MemberDIDenialViewAsync(int seq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberManageService/MemberDIDenialDelete", ReplyAction="http://tempuri.org/IMemberManageService/MemberDIDenialDeleteResponse")]
        void MemberDIDenialDelete(int seq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberManageService/MemberDIDenialDelete", ReplyAction="http://tempuri.org/IMemberManageService/MemberDIDenialDeleteResponse")]
        System.Threading.Tasks.Task MemberDIDenialDeleteAsync(int seq);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMemberManageServiceChannel : Wow.Tv.Admin.MemberManageService.IMemberManageService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MemberManageServiceClient : System.ServiceModel.ClientBase<Wow.Tv.Admin.MemberManageService.IMemberManageService>, Wow.Tv.Admin.MemberManageService.IMemberManageService {
        
        public MemberManageServiceClient() {
        }
        
        public MemberManageServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MemberManageServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MemberManageServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MemberManageServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db89.wowbill.MemberAdminManage.MemberManageListResult> MemberSearchList(Wow.Tv.Middle.Model.Db89.wowbill.MemberAdminManage.MemberManageCondition condition) {
            return base.Channel.MemberSearchList(condition);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db89.wowbill.MemberAdminManage.MemberManageListResult>> MemberSearchListAsync(Wow.Tv.Middle.Model.Db89.wowbill.MemberAdminManage.MemberManageCondition condition) {
            return base.Channel.MemberSearchListAsync(condition);
        }
        
        public Wow.Tv.Middle.Model.Db89.wowbill.MemberAdminManage.MemberManageInfoResult MemberInfo(int userNumber) {
            return base.Channel.MemberInfo(userNumber);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.MemberAdminManage.MemberManageInfoResult> MemberInfoAsync(int userNumber) {
            return base.Channel.MemberInfoAsync(userNumber);
        }
        
        public Wow.Tv.Middle.Model.Db89.wowbill.MemberAdminManage.UserInfoModifyResult MemberInfoSave(Wow.Tv.Middle.Model.Db89.wowbill.MemberAdminManage.UserInfoSaveRequest request) {
            return base.Channel.MemberInfoSave(request);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.MemberAdminManage.UserInfoModifyResult> MemberInfoSaveAsync(Wow.Tv.Middle.Model.Db89.wowbill.MemberAdminManage.UserInfoSaveRequest request) {
            return base.Channel.MemberInfoSaveAsync(request);
        }
        
        public Wow.Tv.Middle.Model.Db89.wowbill.Member.MemberSecessionResult MemberSecession(int userNumber, string secessionReasonKey, string secessionReasonDescription) {
            return base.Channel.MemberSecession(userNumber, secessionReasonKey, secessionReasonDescription);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.Member.MemberSecessionResult> MemberSecessionAsync(int userNumber, string secessionReasonKey, string secessionReasonDescription) {
            return base.Channel.MemberSecessionAsync(userNumber, secessionReasonKey, secessionReasonDescription);
        }
        
        public Wow.Tv.Middle.Model.Db89.wowbill.tblPost[] GetAddress(string searchKeyword) {
            return base.Channel.GetAddress(searchKeyword);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.tblPost[]> GetAddressAsync(string searchKeyword) {
            return base.Channel.GetAddressAsync(searchKeyword);
        }
        
        public Wow.Tv.Middle.Model.Db89.wowbill.MemberAdminManage.MemberInfoStatisticsResult MemberInfoStatistics() {
            return base.Channel.MemberInfoStatistics();
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.MemberAdminManage.MemberInfoStatisticsResult> MemberInfoStatisticsAsync() {
            return base.Channel.MemberInfoStatisticsAsync();
        }
        
        public Wow.Tv.Admin.MemberManageService.SetPasswordResult PasswordInitialize(int userNumber, string adminId) {
            return base.Channel.PasswordInitialize(userNumber, adminId);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Admin.MemberManageService.SetPasswordResult> PasswordInitializeAsync(int userNumber, string adminId) {
            return base.Channel.PasswordInitializeAsync(userNumber, adminId);
        }
        
        public void SendSms(string receiveNo, string callbackNo, string message) {
            base.Channel.SendSms(receiveNo, callbackNo, message);
        }
        
        public System.Threading.Tasks.Task SendSmsAsync(string receiveNo, string callbackNo, string message) {
            return base.Channel.SendSmsAsync(receiveNo, callbackNo, message);
        }
        
        public void UserApproval(int userNumber, bool approved, string reason) {
            base.Channel.UserApproval(userNumber, approved, reason);
        }
        
        public System.Threading.Tasks.Task UserApprovalAsync(int userNumber, bool approved, string reason) {
            return base.Channel.UserApprovalAsync(userNumber, approved, reason);
        }
        
        public Wow.Tv.Middle.Model.Db89.wowbill.MemberAdminManage.MemberInfoSimple[] SimpleMemberList(int[] userNumberList) {
            return base.Channel.SimpleMemberList(userNumberList);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.MemberAdminManage.MemberInfoSimple[]> SimpleMemberListAsync(int[] userNumberList) {
            return base.Channel.SimpleMemberListAsync(userNumberList);
        }
        
        public string RestoreDormancy(int userNumber) {
            return base.Channel.RestoreDormancy(userNumber);
        }
        
        public System.Threading.Tasks.Task<string> RestoreDormancyAsync(int userNumber) {
            return base.Channel.RestoreDormancyAsync(userNumber);
        }
        
        public Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db89.wowbill.TblMemberDIDenialList> MemberDIDenialList(Wow.Tv.Middle.Model.Db49.wowtv.Board.IntegratedBoardCondition condition) {
            return base.Channel.MemberDIDenialList(condition);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db89.wowbill.TblMemberDIDenialList>> MemberDIDenialListAsync(Wow.Tv.Middle.Model.Db49.wowtv.Board.IntegratedBoardCondition condition) {
            return base.Channel.MemberDIDenialListAsync(condition);
        }
        
        public void MemberDIDenialWriteProc(Wow.Tv.Middle.Model.Db89.wowbill.TblMemberDIDenialList model) {
            base.Channel.MemberDIDenialWriteProc(model);
        }
        
        public System.Threading.Tasks.Task MemberDIDenialWriteProcAsync(Wow.Tv.Middle.Model.Db89.wowbill.TblMemberDIDenialList model) {
            return base.Channel.MemberDIDenialWriteProcAsync(model);
        }
        
        public Wow.Tv.Middle.Model.Db89.wowbill.TblMemberDIDenialList MemberDIDenialView(int seq) {
            return base.Channel.MemberDIDenialView(seq);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.TblMemberDIDenialList> MemberDIDenialViewAsync(int seq) {
            return base.Channel.MemberDIDenialViewAsync(seq);
        }
        
        public void MemberDIDenialDelete(int seq) {
            base.Channel.MemberDIDenialDelete(seq);
        }
        
        public System.Threading.Tasks.Task MemberDIDenialDeleteAsync(int seq) {
            return base.Channel.MemberDIDenialDeleteAsync(seq);
        }
    }
}
