//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Admin.MemberMonitoringService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MemberMonitoringService.IMemberMonitoringService")]
    public interface IMemberMonitoringService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberMonitoringService/TotalList", ReplyAction="http://tempuri.org/IMemberMonitoringService/TotalListResponse")]
        Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.MemberManage.TotalListResult> TotalList(Wow.Tv.Middle.Model.Db49.wowtv.MemberManage.TotalListCondition condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberMonitoringService/TotalList", ReplyAction="http://tempuri.org/IMemberMonitoringService/TotalListResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.MemberManage.TotalListResult>> TotalListAsync(Wow.Tv.Middle.Model.Db49.wowtv.MemberManage.TotalListCondition condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberMonitoringService/NewRegCfm", ReplyAction="http://tempuri.org/IMemberMonitoringService/NewRegCfmResponse")]
        Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.MemberManage.NewRegCfmResult> NewRegCfm(Wow.Tv.Middle.Model.Db49.wowtv.MemberManage.NewRegCfmCondition condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberMonitoringService/NewRegCfm", ReplyAction="http://tempuri.org/IMemberMonitoringService/NewRegCfmResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.MemberManage.NewRegCfmResult>> NewRegCfmAsync(Wow.Tv.Middle.Model.Db49.wowtv.MemberManage.NewRegCfmCondition condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberMonitoringService/AccAuth", ReplyAction="http://tempuri.org/IMemberMonitoringService/AccAuthResponse")]
        Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.MemberManage.AccAuthResult> AccAuth(Wow.Tv.Middle.Model.Db49.wowtv.MemberManage.AccAuthCondition condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberMonitoringService/AccAuth", ReplyAction="http://tempuri.org/IMemberMonitoringService/AccAuthResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.MemberManage.AccAuthResult>> AccAuthAsync(Wow.Tv.Middle.Model.Db49.wowtv.MemberManage.AccAuthCondition condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberMonitoringService/AccLog", ReplyAction="http://tempuri.org/IMemberMonitoringService/AccLogResponse")]
        Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.MemberManage.AccLogResult> AccLog(Wow.Tv.Middle.Model.Db49.wowtv.MemberManage.AccLogCondition condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberMonitoringService/AccLog", ReplyAction="http://tempuri.org/IMemberMonitoringService/AccLogResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.MemberManage.AccLogResult>> AccLogAsync(Wow.Tv.Middle.Model.Db49.wowtv.MemberManage.AccLogCondition condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberMonitoringService/WorkOutLogHist", ReplyAction="http://tempuri.org/IMemberMonitoringService/WorkOutLogHistResponse")]
        Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.MemberManage.WorkOutLogHistResult> WorkOutLogHist(Wow.Tv.Middle.Model.Db49.wowtv.MemberManage.WorkOutLogHistCondition condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberMonitoringService/WorkOutLogHist", ReplyAction="http://tempuri.org/IMemberMonitoringService/WorkOutLogHistResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.MemberManage.WorkOutLogHistResult>> WorkOutLogHistAsync(Wow.Tv.Middle.Model.Db49.wowtv.MemberManage.WorkOutLogHistCondition condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberMonitoringService/MemInfoOpenChk", ReplyAction="http://tempuri.org/IMemberMonitoringService/MemInfoOpenChkResponse")]
        Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.MemberManage.MemInfoOpenChkResult> MemInfoOpenChk(Wow.Tv.Middle.Model.Db49.wowtv.MemberManage.MemInfoOpenChkCondition condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberMonitoringService/MemInfoOpenChk", ReplyAction="http://tempuri.org/IMemberMonitoringService/MemInfoOpenChkResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.MemberManage.MemInfoOpenChkResult>> MemInfoOpenChkAsync(Wow.Tv.Middle.Model.Db49.wowtv.MemberManage.MemInfoOpenChkCondition condition);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMemberMonitoringServiceChannel : Wow.Tv.Admin.MemberMonitoringService.IMemberMonitoringService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MemberMonitoringServiceClient : System.ServiceModel.ClientBase<Wow.Tv.Admin.MemberMonitoringService.IMemberMonitoringService>, Wow.Tv.Admin.MemberMonitoringService.IMemberMonitoringService {
        
        public MemberMonitoringServiceClient() {
        }
        
        public MemberMonitoringServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MemberMonitoringServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MemberMonitoringServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MemberMonitoringServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.MemberManage.TotalListResult> TotalList(Wow.Tv.Middle.Model.Db49.wowtv.MemberManage.TotalListCondition condition) {
            return base.Channel.TotalList(condition);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.MemberManage.TotalListResult>> TotalListAsync(Wow.Tv.Middle.Model.Db49.wowtv.MemberManage.TotalListCondition condition) {
            return base.Channel.TotalListAsync(condition);
        }
        
        public Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.MemberManage.NewRegCfmResult> NewRegCfm(Wow.Tv.Middle.Model.Db49.wowtv.MemberManage.NewRegCfmCondition condition) {
            return base.Channel.NewRegCfm(condition);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.MemberManage.NewRegCfmResult>> NewRegCfmAsync(Wow.Tv.Middle.Model.Db49.wowtv.MemberManage.NewRegCfmCondition condition) {
            return base.Channel.NewRegCfmAsync(condition);
        }
        
        public Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.MemberManage.AccAuthResult> AccAuth(Wow.Tv.Middle.Model.Db49.wowtv.MemberManage.AccAuthCondition condition) {
            return base.Channel.AccAuth(condition);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.MemberManage.AccAuthResult>> AccAuthAsync(Wow.Tv.Middle.Model.Db49.wowtv.MemberManage.AccAuthCondition condition) {
            return base.Channel.AccAuthAsync(condition);
        }
        
        public Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.MemberManage.AccLogResult> AccLog(Wow.Tv.Middle.Model.Db49.wowtv.MemberManage.AccLogCondition condition) {
            return base.Channel.AccLog(condition);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.MemberManage.AccLogResult>> AccLogAsync(Wow.Tv.Middle.Model.Db49.wowtv.MemberManage.AccLogCondition condition) {
            return base.Channel.AccLogAsync(condition);
        }
        
        public Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.MemberManage.WorkOutLogHistResult> WorkOutLogHist(Wow.Tv.Middle.Model.Db49.wowtv.MemberManage.WorkOutLogHistCondition condition) {
            return base.Channel.WorkOutLogHist(condition);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.MemberManage.WorkOutLogHistResult>> WorkOutLogHistAsync(Wow.Tv.Middle.Model.Db49.wowtv.MemberManage.WorkOutLogHistCondition condition) {
            return base.Channel.WorkOutLogHistAsync(condition);
        }
        
        public Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.MemberManage.MemInfoOpenChkResult> MemInfoOpenChk(Wow.Tv.Middle.Model.Db49.wowtv.MemberManage.MemInfoOpenChkCondition condition) {
            return base.Channel.MemInfoOpenChk(condition);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.MemberManage.MemInfoOpenChkResult>> MemInfoOpenChkAsync(Wow.Tv.Middle.Model.Db49.wowtv.MemberManage.MemInfoOpenChkCondition condition) {
            return base.Channel.MemInfoOpenChkAsync(condition);
        }
    }
}
