//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Admin.TradingStarService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TradingStarService.ITradingStarService")]
    public interface ITradingStarService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITradingStarService/CategoryList", ReplyAction="http://tempuri.org/ITradingStarService/CategoryListResponse")]
        Wow.Tv.Middle.Model.Db49.wowtv.tblTradingStarCategory[] CategoryList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITradingStarService/CategoryList", ReplyAction="http://tempuri.org/ITradingStarService/CategoryListResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.tblTradingStarCategory[]> CategoryListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITradingStarService/GetCategory", ReplyAction="http://tempuri.org/ITradingStarService/GetCategoryResponse")]
        Wow.Tv.Middle.Model.Db49.wowtv.tblTradingStarCategory GetCategory(string tradingCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITradingStarService/GetCategory", ReplyAction="http://tempuri.org/ITradingStarService/GetCategoryResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.tblTradingStarCategory> GetCategoryAsync(string tradingCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITradingStarService/CategorySave", ReplyAction="http://tempuri.org/ITradingStarService/CategorySaveResponse")]
        void CategorySave(Wow.Tv.Middle.Model.Db49.wowtv.tblTradingStarCategory tradingstarCategory, Wow.Tv.Middle.Model.Common.LoginUser loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITradingStarService/CategorySave", ReplyAction="http://tempuri.org/ITradingStarService/CategorySaveResponse")]
        System.Threading.Tasks.Task CategorySaveAsync(Wow.Tv.Middle.Model.Db49.wowtv.tblTradingStarCategory tradingstarCategory, Wow.Tv.Middle.Model.Common.LoginUser loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITradingStarService/UserList", ReplyAction="http://tempuri.org/ITradingStarService/UserListResponse")]
        Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.tblTradingStarUser> UserList(Wow.Tv.Middle.Model.Db49.wowtv.TradingStar.TradingStarCondition condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITradingStarService/UserList", ReplyAction="http://tempuri.org/ITradingStarService/UserListResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.tblTradingStarUser>> UserListAsync(Wow.Tv.Middle.Model.Db49.wowtv.TradingStar.TradingStarCondition condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITradingStarService/UserDelete", ReplyAction="http://tempuri.org/ITradingStarService/UserDeleteResponse")]
        void UserDelete(int seq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITradingStarService/UserDelete", ReplyAction="http://tempuri.org/ITradingStarService/UserDeleteResponse")]
        System.Threading.Tasks.Task UserDeleteAsync(int seq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITradingStarService/UserSave", ReplyAction="http://tempuri.org/ITradingStarService/UserSaveResponse")]
        void UserSave(Wow.Tv.Middle.Model.Db49.wowtv.tblTradingStarUser tradingStarUser, Wow.Tv.Middle.Model.Common.LoginUser loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITradingStarService/UserSave", ReplyAction="http://tempuri.org/ITradingStarService/UserSaveResponse")]
        System.Threading.Tasks.Task UserSaveAsync(Wow.Tv.Middle.Model.Db49.wowtv.tblTradingStarUser tradingStarUser, Wow.Tv.Middle.Model.Common.LoginUser loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITradingStarService/GetUser", ReplyAction="http://tempuri.org/ITradingStarService/GetUserResponse")]
        Wow.Tv.Middle.Model.Db49.wowtv.tblTradingStarUser GetUser(int seq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITradingStarService/GetUser", ReplyAction="http://tempuri.org/ITradingStarService/GetUserResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.tblTradingStarUser> GetUserAsync(int seq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITradingStarService/TradeList", ReplyAction="http://tempuri.org/ITradingStarService/TradeListResponse")]
        Wow.Tv.Middle.Model.Db49.wowtv.tblTradingStarTrade[] TradeList(int regseq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITradingStarService/TradeList", ReplyAction="http://tempuri.org/ITradingStarService/TradeListResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.tblTradingStarTrade[]> TradeListAsync(int regseq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITradingStarService/TradeDelete", ReplyAction="http://tempuri.org/ITradingStarService/TradeDeleteResponse")]
        void TradeDelete(int seq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITradingStarService/TradeDelete", ReplyAction="http://tempuri.org/ITradingStarService/TradeDeleteResponse")]
        System.Threading.Tasks.Task TradeDeleteAsync(int seq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITradingStarService/TradeSave", ReplyAction="http://tempuri.org/ITradingStarService/TradeSaveResponse")]
        void TradeSave(Wow.Tv.Middle.Model.Db49.wowtv.tblTradingStarTrade tradingStarUser, Wow.Tv.Middle.Model.Common.LoginUser loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITradingStarService/TradeSave", ReplyAction="http://tempuri.org/ITradingStarService/TradeSaveResponse")]
        System.Threading.Tasks.Task TradeSaveAsync(Wow.Tv.Middle.Model.Db49.wowtv.tblTradingStarTrade tradingStarUser, Wow.Tv.Middle.Model.Common.LoginUser loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITradingStarService/GetTrade", ReplyAction="http://tempuri.org/ITradingStarService/GetTradeResponse")]
        Wow.Tv.Middle.Model.Db49.wowtv.tblTradingStarTrade GetTrade(int seq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITradingStarService/GetTrade", ReplyAction="http://tempuri.org/ITradingStarService/GetTradeResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.tblTradingStarTrade> GetTradeAsync(int seq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITradingStarService/CurrentStockPriceList", ReplyAction="http://tempuri.org/ITradingStarService/CurrentStockPriceListResponse")]
        Wow.Tv.Middle.Model.Db22.stock.tblOnlineSise[] CurrentStockPriceList(string korname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITradingStarService/CurrentStockPriceList", ReplyAction="http://tempuri.org/ITradingStarService/CurrentStockPriceListResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db22.stock.tblOnlineSise[]> CurrentStockPriceListAsync(string korname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITradingStarService/UpdateEarningRate", ReplyAction="http://tempuri.org/ITradingStarService/UpdateEarningRateResponse")]
        void UpdateEarningRate(int seq, double earningRateSum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITradingStarService/UpdateEarningRate", ReplyAction="http://tempuri.org/ITradingStarService/UpdateEarningRateResponse")]
        System.Threading.Tasks.Task UpdateEarningRateAsync(int seq, double earningRateSum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITradingStarService/UpdateTotalHavaRateText", ReplyAction="http://tempuri.org/ITradingStarService/UpdateTotalHavaRateTextResponse")]
        void UpdateTotalHavaRateText(int regSeq, double totalHavaRateText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITradingStarService/UpdateTotalHavaRateText", ReplyAction="http://tempuri.org/ITradingStarService/UpdateTotalHavaRateTextResponse")]
        System.Threading.Tasks.Task UpdateTotalHavaRateTextAsync(int regSeq, double totalHavaRateText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITradingStarService/GetStockList", ReplyAction="http://tempuri.org/ITradingStarService/GetStockListResponse")]
        Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db22.stock.tblStockBatch> GetStockList(Wow.Tv.Middle.Model.Db22.Admin.StockBatchCondition condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITradingStarService/GetStockList", ReplyAction="http://tempuri.org/ITradingStarService/GetStockListResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db22.stock.tblStockBatch>> GetStockListAsync(Wow.Tv.Middle.Model.Db22.Admin.StockBatchCondition condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITradingStarService/UpdateStarMark", ReplyAction="http://tempuri.org/ITradingStarService/UpdateStarMarkResponse")]
        void UpdateStarMark(int seq, float starMark);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITradingStarService/UpdateStarMark", ReplyAction="http://tempuri.org/ITradingStarService/UpdateStarMarkResponse")]
        System.Threading.Tasks.Task UpdateStarMarkAsync(int seq, float starMark);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITradingStarServiceChannel : Wow.Tv.Admin.TradingStarService.ITradingStarService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TradingStarServiceClient : System.ServiceModel.ClientBase<Wow.Tv.Admin.TradingStarService.ITradingStarService>, Wow.Tv.Admin.TradingStarService.ITradingStarService {
        
        public TradingStarServiceClient() {
        }
        
        public TradingStarServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TradingStarServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TradingStarServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TradingStarServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Wow.Tv.Middle.Model.Db49.wowtv.tblTradingStarCategory[] CategoryList() {
            return base.Channel.CategoryList();
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.tblTradingStarCategory[]> CategoryListAsync() {
            return base.Channel.CategoryListAsync();
        }
        
        public Wow.Tv.Middle.Model.Db49.wowtv.tblTradingStarCategory GetCategory(string tradingCode) {
            return base.Channel.GetCategory(tradingCode);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.tblTradingStarCategory> GetCategoryAsync(string tradingCode) {
            return base.Channel.GetCategoryAsync(tradingCode);
        }
        
        public void CategorySave(Wow.Tv.Middle.Model.Db49.wowtv.tblTradingStarCategory tradingstarCategory, Wow.Tv.Middle.Model.Common.LoginUser loginUser) {
            base.Channel.CategorySave(tradingstarCategory, loginUser);
        }
        
        public System.Threading.Tasks.Task CategorySaveAsync(Wow.Tv.Middle.Model.Db49.wowtv.tblTradingStarCategory tradingstarCategory, Wow.Tv.Middle.Model.Common.LoginUser loginUser) {
            return base.Channel.CategorySaveAsync(tradingstarCategory, loginUser);
        }
        
        public Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.tblTradingStarUser> UserList(Wow.Tv.Middle.Model.Db49.wowtv.TradingStar.TradingStarCondition condition) {
            return base.Channel.UserList(condition);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.tblTradingStarUser>> UserListAsync(Wow.Tv.Middle.Model.Db49.wowtv.TradingStar.TradingStarCondition condition) {
            return base.Channel.UserListAsync(condition);
        }
        
        public void UserDelete(int seq) {
            base.Channel.UserDelete(seq);
        }
        
        public System.Threading.Tasks.Task UserDeleteAsync(int seq) {
            return base.Channel.UserDeleteAsync(seq);
        }
        
        public void UserSave(Wow.Tv.Middle.Model.Db49.wowtv.tblTradingStarUser tradingStarUser, Wow.Tv.Middle.Model.Common.LoginUser loginUser) {
            base.Channel.UserSave(tradingStarUser, loginUser);
        }
        
        public System.Threading.Tasks.Task UserSaveAsync(Wow.Tv.Middle.Model.Db49.wowtv.tblTradingStarUser tradingStarUser, Wow.Tv.Middle.Model.Common.LoginUser loginUser) {
            return base.Channel.UserSaveAsync(tradingStarUser, loginUser);
        }
        
        public Wow.Tv.Middle.Model.Db49.wowtv.tblTradingStarUser GetUser(int seq) {
            return base.Channel.GetUser(seq);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.tblTradingStarUser> GetUserAsync(int seq) {
            return base.Channel.GetUserAsync(seq);
        }
        
        public Wow.Tv.Middle.Model.Db49.wowtv.tblTradingStarTrade[] TradeList(int regseq) {
            return base.Channel.TradeList(regseq);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.tblTradingStarTrade[]> TradeListAsync(int regseq) {
            return base.Channel.TradeListAsync(regseq);
        }
        
        public void TradeDelete(int seq) {
            base.Channel.TradeDelete(seq);
        }
        
        public System.Threading.Tasks.Task TradeDeleteAsync(int seq) {
            return base.Channel.TradeDeleteAsync(seq);
        }
        
        public void TradeSave(Wow.Tv.Middle.Model.Db49.wowtv.tblTradingStarTrade tradingStarUser, Wow.Tv.Middle.Model.Common.LoginUser loginUser) {
            base.Channel.TradeSave(tradingStarUser, loginUser);
        }
        
        public System.Threading.Tasks.Task TradeSaveAsync(Wow.Tv.Middle.Model.Db49.wowtv.tblTradingStarTrade tradingStarUser, Wow.Tv.Middle.Model.Common.LoginUser loginUser) {
            return base.Channel.TradeSaveAsync(tradingStarUser, loginUser);
        }
        
        public Wow.Tv.Middle.Model.Db49.wowtv.tblTradingStarTrade GetTrade(int seq) {
            return base.Channel.GetTrade(seq);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.tblTradingStarTrade> GetTradeAsync(int seq) {
            return base.Channel.GetTradeAsync(seq);
        }
        
        public Wow.Tv.Middle.Model.Db22.stock.tblOnlineSise[] CurrentStockPriceList(string korname) {
            return base.Channel.CurrentStockPriceList(korname);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db22.stock.tblOnlineSise[]> CurrentStockPriceListAsync(string korname) {
            return base.Channel.CurrentStockPriceListAsync(korname);
        }
        
        public void UpdateEarningRate(int seq, double earningRateSum) {
            base.Channel.UpdateEarningRate(seq, earningRateSum);
        }
        
        public System.Threading.Tasks.Task UpdateEarningRateAsync(int seq, double earningRateSum) {
            return base.Channel.UpdateEarningRateAsync(seq, earningRateSum);
        }
        
        public void UpdateTotalHavaRateText(int regSeq, double totalHavaRateText) {
            base.Channel.UpdateTotalHavaRateText(regSeq, totalHavaRateText);
        }
        
        public System.Threading.Tasks.Task UpdateTotalHavaRateTextAsync(int regSeq, double totalHavaRateText) {
            return base.Channel.UpdateTotalHavaRateTextAsync(regSeq, totalHavaRateText);
        }
        
        public Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db22.stock.tblStockBatch> GetStockList(Wow.Tv.Middle.Model.Db22.Admin.StockBatchCondition condition) {
            return base.Channel.GetStockList(condition);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db22.stock.tblStockBatch>> GetStockListAsync(Wow.Tv.Middle.Model.Db22.Admin.StockBatchCondition condition) {
            return base.Channel.GetStockListAsync(condition);
        }
        
        public void UpdateStarMark(int seq, float starMark) {
            base.Channel.UpdateStarMark(seq, starMark);
        }
        
        public System.Threading.Tasks.Task UpdateStarMarkAsync(int seq, float starMark) {
            return base.Channel.UpdateStarMarkAsync(seq, starMark);
        }
    }
}
