//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Admin.FamilyService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FamilyService.IFamilyService")]
    public interface IFamilyService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFamilyService/SearchList", ReplyAction="http://tempuri.org/IFamilyService/SearchListResponse")]
        Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.NTB_FAMILY> SearchList(Wow.Tv.Middle.Model.Db49.wowtv.Family.FamilyCondition condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFamilyService/SearchList", ReplyAction="http://tempuri.org/IFamilyService/SearchListResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.NTB_FAMILY>> SearchListAsync(Wow.Tv.Middle.Model.Db49.wowtv.Family.FamilyCondition condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFamilyService/GetAt", ReplyAction="http://tempuri.org/IFamilyService/GetAtResponse")]
        Wow.Tv.Middle.Model.Db49.wowtv.NTB_FAMILY GetAt(int familySeq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFamilyService/GetAt", ReplyAction="http://tempuri.org/IFamilyService/GetAtResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.NTB_FAMILY> GetAtAsync(int familySeq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFamilyService/Save", ReplyAction="http://tempuri.org/IFamilyService/SaveResponse")]
        int Save(Wow.Tv.Middle.Model.Db49.wowtv.NTB_FAMILY model, Wow.Tv.Middle.Model.Common.LoginUser loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFamilyService/Save", ReplyAction="http://tempuri.org/IFamilyService/SaveResponse")]
        System.Threading.Tasks.Task<int> SaveAsync(Wow.Tv.Middle.Model.Db49.wowtv.NTB_FAMILY model, Wow.Tv.Middle.Model.Common.LoginUser loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFamilyService/Delete", ReplyAction="http://tempuri.org/IFamilyService/DeleteResponse")]
        void Delete(int familySeq, Wow.Tv.Middle.Model.Common.LoginUser loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFamilyService/Delete", ReplyAction="http://tempuri.org/IFamilyService/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(int familySeq, Wow.Tv.Middle.Model.Common.LoginUser loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFamilyService/DeleteList", ReplyAction="http://tempuri.org/IFamilyService/DeleteListResponse")]
        void DeleteList(int[] seqList, Wow.Tv.Middle.Model.Common.LoginUser loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFamilyService/DeleteList", ReplyAction="http://tempuri.org/IFamilyService/DeleteListResponse")]
        System.Threading.Tasks.Task DeleteListAsync(int[] seqList, Wow.Tv.Middle.Model.Common.LoginUser loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFamilyService/UpDown", ReplyAction="http://tempuri.org/IFamilyService/UpDownResponse")]
        void UpDown(int familySeq, bool isUp, Wow.Tv.Middle.Model.Common.LoginUser loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFamilyService/UpDown", ReplyAction="http://tempuri.org/IFamilyService/UpDownResponse")]
        System.Threading.Tasks.Task UpDownAsync(int familySeq, bool isUp, Wow.Tv.Middle.Model.Common.LoginUser loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFamilyService/ExcelExport", ReplyAction="http://tempuri.org/IFamilyService/ExcelExportResponse")]
        System.IO.MemoryStream ExcelExport(Wow.Tv.Middle.Model.Db49.wowtv.Family.FamilyCondition condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFamilyService/ExcelExport", ReplyAction="http://tempuri.org/IFamilyService/ExcelExportResponse")]
        System.Threading.Tasks.Task<System.IO.MemoryStream> ExcelExportAsync(Wow.Tv.Middle.Model.Db49.wowtv.Family.FamilyCondition condition);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFamilyServiceChannel : Wow.Tv.Admin.FamilyService.IFamilyService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FamilyServiceClient : System.ServiceModel.ClientBase<Wow.Tv.Admin.FamilyService.IFamilyService>, Wow.Tv.Admin.FamilyService.IFamilyService {
        
        public FamilyServiceClient() {
        }
        
        public FamilyServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FamilyServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FamilyServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FamilyServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.NTB_FAMILY> SearchList(Wow.Tv.Middle.Model.Db49.wowtv.Family.FamilyCondition condition) {
            return base.Channel.SearchList(condition);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.NTB_FAMILY>> SearchListAsync(Wow.Tv.Middle.Model.Db49.wowtv.Family.FamilyCondition condition) {
            return base.Channel.SearchListAsync(condition);
        }
        
        public Wow.Tv.Middle.Model.Db49.wowtv.NTB_FAMILY GetAt(int familySeq) {
            return base.Channel.GetAt(familySeq);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.NTB_FAMILY> GetAtAsync(int familySeq) {
            return base.Channel.GetAtAsync(familySeq);
        }
        
        public int Save(Wow.Tv.Middle.Model.Db49.wowtv.NTB_FAMILY model, Wow.Tv.Middle.Model.Common.LoginUser loginUser) {
            return base.Channel.Save(model, loginUser);
        }
        
        public System.Threading.Tasks.Task<int> SaveAsync(Wow.Tv.Middle.Model.Db49.wowtv.NTB_FAMILY model, Wow.Tv.Middle.Model.Common.LoginUser loginUser) {
            return base.Channel.SaveAsync(model, loginUser);
        }
        
        public void Delete(int familySeq, Wow.Tv.Middle.Model.Common.LoginUser loginUser) {
            base.Channel.Delete(familySeq, loginUser);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(int familySeq, Wow.Tv.Middle.Model.Common.LoginUser loginUser) {
            return base.Channel.DeleteAsync(familySeq, loginUser);
        }
        
        public void DeleteList(int[] seqList, Wow.Tv.Middle.Model.Common.LoginUser loginUser) {
            base.Channel.DeleteList(seqList, loginUser);
        }
        
        public System.Threading.Tasks.Task DeleteListAsync(int[] seqList, Wow.Tv.Middle.Model.Common.LoginUser loginUser) {
            return base.Channel.DeleteListAsync(seqList, loginUser);
        }
        
        public void UpDown(int familySeq, bool isUp, Wow.Tv.Middle.Model.Common.LoginUser loginUser) {
            base.Channel.UpDown(familySeq, isUp, loginUser);
        }
        
        public System.Threading.Tasks.Task UpDownAsync(int familySeq, bool isUp, Wow.Tv.Middle.Model.Common.LoginUser loginUser) {
            return base.Channel.UpDownAsync(familySeq, isUp, loginUser);
        }
        
        public System.IO.MemoryStream ExcelExport(Wow.Tv.Middle.Model.Db49.wowtv.Family.FamilyCondition condition) {
            return base.Channel.ExcelExport(condition);
        }
        
        public System.Threading.Tasks.Task<System.IO.MemoryStream> ExcelExportAsync(Wow.Tv.Middle.Model.Db49.wowtv.Family.FamilyCondition condition) {
            return base.Channel.ExcelExportAsync(condition);
        }
    }
}
