//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Admin.ActionLogService {
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ActionLogBiz.ActionCode", Namespace="http://schemas.datacontract.org/2004/07/Wow.Tv.Middle.Biz.ActionLog")]
    public enum ActionLogBizActionCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Insert = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Update = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Delete = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Select = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Excel = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ActionLogService.IActionLogService")]
    public interface IActionLogService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActionLogService/Create", ReplyAction="http://tempuri.org/IActionLogService/CreateResponse")]
        void Create(string menuSeq, string tableKey, Wow.Tv.Admin.ActionLogService.ActionLogBizActionCode actionCode, string addInfo1, string addInfo2, Wow.Tv.Middle.Model.Common.LoginUser loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActionLogService/Create", ReplyAction="http://tempuri.org/IActionLogService/CreateResponse")]
        System.Threading.Tasks.Task CreateAsync(string menuSeq, string tableKey, Wow.Tv.Admin.ActionLogService.ActionLogBizActionCode actionCode, string addInfo1, string addInfo2, Wow.Tv.Middle.Model.Common.LoginUser loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActionLogService/CreateIUCheck", ReplyAction="http://tempuri.org/IActionLogService/CreateIUCheckResponse")]
        void CreateIUCheck(string menuSeq, string tableKey, string addInfo1, string addInfo2, Wow.Tv.Middle.Model.Common.LoginUser loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActionLogService/CreateIUCheck", ReplyAction="http://tempuri.org/IActionLogService/CreateIUCheckResponse")]
        System.Threading.Tasks.Task CreateIUCheckAsync(string menuSeq, string tableKey, string addInfo1, string addInfo2, Wow.Tv.Middle.Model.Common.LoginUser loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActionLogService/SearchList", ReplyAction="http://tempuri.org/IActionLogService/SearchListResponse")]
        Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.NTB_ACTION_LOG> SearchList(Wow.Tv.Middle.Model.Db49.wowtv.ActionLog.ActionLogCondition condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActionLogService/SearchList", ReplyAction="http://tempuri.org/IActionLogService/SearchListResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.NTB_ACTION_LOG>> SearchListAsync(Wow.Tv.Middle.Model.Db49.wowtv.ActionLog.ActionLogCondition condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActionLogService/ExcelExport", ReplyAction="http://tempuri.org/IActionLogService/ExcelExportResponse")]
        System.IO.MemoryStream ExcelExport(Wow.Tv.Middle.Model.Db49.wowtv.ActionLog.ActionLogCondition condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActionLogService/ExcelExport", ReplyAction="http://tempuri.org/IActionLogService/ExcelExportResponse")]
        System.Threading.Tasks.Task<System.IO.MemoryStream> ExcelExportAsync(Wow.Tv.Middle.Model.Db49.wowtv.ActionLog.ActionLogCondition condition);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IActionLogServiceChannel : Wow.Tv.Admin.ActionLogService.IActionLogService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ActionLogServiceClient : System.ServiceModel.ClientBase<Wow.Tv.Admin.ActionLogService.IActionLogService>, Wow.Tv.Admin.ActionLogService.IActionLogService {
        
        public ActionLogServiceClient() {
        }
        
        public ActionLogServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ActionLogServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ActionLogServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ActionLogServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Create(string menuSeq, string tableKey, Wow.Tv.Admin.ActionLogService.ActionLogBizActionCode actionCode, string addInfo1, string addInfo2, Wow.Tv.Middle.Model.Common.LoginUser loginUser) {
            base.Channel.Create(menuSeq, tableKey, actionCode, addInfo1, addInfo2, loginUser);
        }
        
        public System.Threading.Tasks.Task CreateAsync(string menuSeq, string tableKey, Wow.Tv.Admin.ActionLogService.ActionLogBizActionCode actionCode, string addInfo1, string addInfo2, Wow.Tv.Middle.Model.Common.LoginUser loginUser) {
            return base.Channel.CreateAsync(menuSeq, tableKey, actionCode, addInfo1, addInfo2, loginUser);
        }
        
        public void CreateIUCheck(string menuSeq, string tableKey, string addInfo1, string addInfo2, Wow.Tv.Middle.Model.Common.LoginUser loginUser) {
            base.Channel.CreateIUCheck(menuSeq, tableKey, addInfo1, addInfo2, loginUser);
        }
        
        public System.Threading.Tasks.Task CreateIUCheckAsync(string menuSeq, string tableKey, string addInfo1, string addInfo2, Wow.Tv.Middle.Model.Common.LoginUser loginUser) {
            return base.Channel.CreateIUCheckAsync(menuSeq, tableKey, addInfo1, addInfo2, loginUser);
        }
        
        public Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.NTB_ACTION_LOG> SearchList(Wow.Tv.Middle.Model.Db49.wowtv.ActionLog.ActionLogCondition condition) {
            return base.Channel.SearchList(condition);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.NTB_ACTION_LOG>> SearchListAsync(Wow.Tv.Middle.Model.Db49.wowtv.ActionLog.ActionLogCondition condition) {
            return base.Channel.SearchListAsync(condition);
        }
        
        public System.IO.MemoryStream ExcelExport(Wow.Tv.Middle.Model.Db49.wowtv.ActionLog.ActionLogCondition condition) {
            return base.Channel.ExcelExport(condition);
        }
        
        public System.Threading.Tasks.Task<System.IO.MemoryStream> ExcelExportAsync(Wow.Tv.Middle.Model.Db49.wowtv.ActionLog.ActionLogCondition condition) {
            return base.Channel.ExcelExportAsync(condition);
        }
    }
}
