//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Admin.StockholderBoardService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StockholderBoardService.IStockholderBoardService")]
    public interface IStockholderBoardService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockholderBoardService/GetList", ReplyAction="http://tempuri.org/IStockholderBoardService/GetListResponse")]
        Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.StockholderBoard.StockholderBoard> GetList(Wow.Tv.Middle.Model.Db49.wowtv.StockholderBoard.StockholderBoardCondition condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockholderBoardService/GetList", ReplyAction="http://tempuri.org/IStockholderBoardService/GetListResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.StockholderBoard.StockholderBoard>> GetListAsync(Wow.Tv.Middle.Model.Db49.wowtv.StockholderBoard.StockholderBoardCondition condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockholderBoardService/GetDetail", ReplyAction="http://tempuri.org/IStockholderBoardService/GetDetailResponse")]
        Wow.Tv.Middle.Model.Db49.wowtv.StockholderBoard.StockholderBoard GetDetail(int seq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockholderBoardService/GetDetail", ReplyAction="http://tempuri.org/IStockholderBoardService/GetDetailResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.StockholderBoard.StockholderBoard> GetDetailAsync(int seq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockholderBoardService/BoardSave", ReplyAction="http://tempuri.org/IStockholderBoardService/BoardSaveResponse")]
        void BoardSave(Wow.Tv.Middle.Model.Db49.wowtv.NTB_STOCKHOLDER_BOARD model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockholderBoardService/BoardSave", ReplyAction="http://tempuri.org/IStockholderBoardService/BoardSaveResponse")]
        System.Threading.Tasks.Task BoardSaveAsync(Wow.Tv.Middle.Model.Db49.wowtv.NTB_STOCKHOLDER_BOARD model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockholderBoardService/ReplySave", ReplyAction="http://tempuri.org/IStockholderBoardService/ReplySaveResponse")]
        int ReplySave(Wow.Tv.Middle.Model.Db49.wowtv.NTB_STOCKHOLDER_BOARD model, Wow.Tv.Middle.Model.Common.LoginUser loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockholderBoardService/ReplySave", ReplyAction="http://tempuri.org/IStockholderBoardService/ReplySaveResponse")]
        System.Threading.Tasks.Task<int> ReplySaveAsync(Wow.Tv.Middle.Model.Db49.wowtv.NTB_STOCKHOLDER_BOARD model, Wow.Tv.Middle.Model.Common.LoginUser loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockholderBoardService/Delete", ReplyAction="http://tempuri.org/IStockholderBoardService/DeleteResponse")]
        void Delete(int[] deleteList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockholderBoardService/Delete", ReplyAction="http://tempuri.org/IStockholderBoardService/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(int[] deleteList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockholderBoardService/UpdateBlind", ReplyAction="http://tempuri.org/IStockholderBoardService/UpdateBlindResponse")]
        void UpdateBlind(int seq, string blindYn, Wow.Tv.Middle.Model.Common.LoginUser loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockholderBoardService/UpdateBlind", ReplyAction="http://tempuri.org/IStockholderBoardService/UpdateBlindResponse")]
        System.Threading.Tasks.Task UpdateBlindAsync(int seq, string blindYn, Wow.Tv.Middle.Model.Common.LoginUser loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockholderBoardService/UpdateReadCnt", ReplyAction="http://tempuri.org/IStockholderBoardService/UpdateReadCntResponse")]
        void UpdateReadCnt(int seq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockholderBoardService/UpdateReadCnt", ReplyAction="http://tempuri.org/IStockholderBoardService/UpdateReadCntResponse")]
        System.Threading.Tasks.Task UpdateReadCntAsync(int seq);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStockholderBoardServiceChannel : Wow.Tv.Admin.StockholderBoardService.IStockholderBoardService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StockholderBoardServiceClient : System.ServiceModel.ClientBase<Wow.Tv.Admin.StockholderBoardService.IStockholderBoardService>, Wow.Tv.Admin.StockholderBoardService.IStockholderBoardService {
        
        public StockholderBoardServiceClient() {
        }
        
        public StockholderBoardServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StockholderBoardServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StockholderBoardServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StockholderBoardServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.StockholderBoard.StockholderBoard> GetList(Wow.Tv.Middle.Model.Db49.wowtv.StockholderBoard.StockholderBoardCondition condition) {
            return base.Channel.GetList(condition);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.StockholderBoard.StockholderBoard>> GetListAsync(Wow.Tv.Middle.Model.Db49.wowtv.StockholderBoard.StockholderBoardCondition condition) {
            return base.Channel.GetListAsync(condition);
        }
        
        public Wow.Tv.Middle.Model.Db49.wowtv.StockholderBoard.StockholderBoard GetDetail(int seq) {
            return base.Channel.GetDetail(seq);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.StockholderBoard.StockholderBoard> GetDetailAsync(int seq) {
            return base.Channel.GetDetailAsync(seq);
        }
        
        public void BoardSave(Wow.Tv.Middle.Model.Db49.wowtv.NTB_STOCKHOLDER_BOARD model) {
            base.Channel.BoardSave(model);
        }
        
        public System.Threading.Tasks.Task BoardSaveAsync(Wow.Tv.Middle.Model.Db49.wowtv.NTB_STOCKHOLDER_BOARD model) {
            return base.Channel.BoardSaveAsync(model);
        }
        
        public int ReplySave(Wow.Tv.Middle.Model.Db49.wowtv.NTB_STOCKHOLDER_BOARD model, Wow.Tv.Middle.Model.Common.LoginUser loginUser) {
            return base.Channel.ReplySave(model, loginUser);
        }
        
        public System.Threading.Tasks.Task<int> ReplySaveAsync(Wow.Tv.Middle.Model.Db49.wowtv.NTB_STOCKHOLDER_BOARD model, Wow.Tv.Middle.Model.Common.LoginUser loginUser) {
            return base.Channel.ReplySaveAsync(model, loginUser);
        }
        
        public void Delete(int[] deleteList) {
            base.Channel.Delete(deleteList);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(int[] deleteList) {
            return base.Channel.DeleteAsync(deleteList);
        }
        
        public void UpdateBlind(int seq, string blindYn, Wow.Tv.Middle.Model.Common.LoginUser loginUser) {
            base.Channel.UpdateBlind(seq, blindYn, loginUser);
        }
        
        public System.Threading.Tasks.Task UpdateBlindAsync(int seq, string blindYn, Wow.Tv.Middle.Model.Common.LoginUser loginUser) {
            return base.Channel.UpdateBlindAsync(seq, blindYn, loginUser);
        }
        
        public void UpdateReadCnt(int seq) {
            base.Channel.UpdateReadCnt(seq);
        }
        
        public System.Threading.Tasks.Task UpdateReadCntAsync(int seq) {
            return base.Channel.UpdateReadCntAsync(seq);
        }
    }
}
