//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Admin.CTGRManageService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CTGRManageService.ICTGRManageService")]
    public interface ICTGRManageService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICTGRManageService/GetList", ReplyAction="http://tempuri.org/ICTGRManageService/GetListResponse")]
        Wow.Tv.Middle.Model.Db49.wowtv.History.CTGRModel<Wow.Tv.Middle.Model.Db49.wowtv.NTB_CTGR> GetList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICTGRManageService/GetList", ReplyAction="http://tempuri.org/ICTGRManageService/GetListResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.History.CTGRModel<Wow.Tv.Middle.Model.Db49.wowtv.NTB_CTGR>> GetListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICTGRManageService/Save", ReplyAction="http://tempuri.org/ICTGRManageService/SaveResponse")]
        int Save(Wow.Tv.Middle.Model.Db49.wowtv.NTB_CTGR model, Wow.Tv.Middle.Model.Common.LoginUser loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICTGRManageService/Save", ReplyAction="http://tempuri.org/ICTGRManageService/SaveResponse")]
        System.Threading.Tasks.Task<int> SaveAsync(Wow.Tv.Middle.Model.Db49.wowtv.NTB_CTGR model, Wow.Tv.Middle.Model.Common.LoginUser loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICTGRManageService/Delete", ReplyAction="http://tempuri.org/ICTGRManageService/DeleteResponse")]
        void Delete(int seq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICTGRManageService/Delete", ReplyAction="http://tempuri.org/ICTGRManageService/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(int seq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICTGRManageService/GetMaxYear", ReplyAction="http://tempuri.org/ICTGRManageService/GetMaxYearResponse")]
        int GetMaxYear();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICTGRManageService/GetMaxYear", ReplyAction="http://tempuri.org/ICTGRManageService/GetMaxYearResponse")]
        System.Threading.Tasks.Task<int> GetMaxYearAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICTGRManageService/GetCTGRList", ReplyAction="http://tempuri.org/ICTGRManageService/GetCTGRListResponse")]
        Wow.Tv.Middle.Model.Db49.wowtv.NTB_CTGR[] GetCTGRList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICTGRManageService/GetCTGRList", ReplyAction="http://tempuri.org/ICTGRManageService/GetCTGRListResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.NTB_CTGR[]> GetCTGRListAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICTGRManageServiceChannel : Wow.Tv.Admin.CTGRManageService.ICTGRManageService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CTGRManageServiceClient : System.ServiceModel.ClientBase<Wow.Tv.Admin.CTGRManageService.ICTGRManageService>, Wow.Tv.Admin.CTGRManageService.ICTGRManageService {
        
        public CTGRManageServiceClient() {
        }
        
        public CTGRManageServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CTGRManageServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CTGRManageServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CTGRManageServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Wow.Tv.Middle.Model.Db49.wowtv.History.CTGRModel<Wow.Tv.Middle.Model.Db49.wowtv.NTB_CTGR> GetList() {
            return base.Channel.GetList();
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.History.CTGRModel<Wow.Tv.Middle.Model.Db49.wowtv.NTB_CTGR>> GetListAsync() {
            return base.Channel.GetListAsync();
        }
        
        public int Save(Wow.Tv.Middle.Model.Db49.wowtv.NTB_CTGR model, Wow.Tv.Middle.Model.Common.LoginUser loginUser) {
            return base.Channel.Save(model, loginUser);
        }
        
        public System.Threading.Tasks.Task<int> SaveAsync(Wow.Tv.Middle.Model.Db49.wowtv.NTB_CTGR model, Wow.Tv.Middle.Model.Common.LoginUser loginUser) {
            return base.Channel.SaveAsync(model, loginUser);
        }
        
        public void Delete(int seq) {
            base.Channel.Delete(seq);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(int seq) {
            return base.Channel.DeleteAsync(seq);
        }
        
        public int GetMaxYear() {
            return base.Channel.GetMaxYear();
        }
        
        public System.Threading.Tasks.Task<int> GetMaxYearAsync() {
            return base.Channel.GetMaxYearAsync();
        }
        
        public Wow.Tv.Middle.Model.Db49.wowtv.NTB_CTGR[] GetCTGRList() {
            return base.Channel.GetCTGRList();
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.NTB_CTGR[]> GetCTGRListAsync() {
            return base.Channel.GetCTGRListAsync();
        }
    }
}
