//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Admin.GroupService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GroupService.IGroupService")]
    public interface IGroupService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupService/SearchList", ReplyAction="http://tempuri.org/IGroupService/SearchListResponse")]
        Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.NTB_GROUP> SearchList(Wow.Tv.Middle.Model.Db49.wowtv.Group.GroupCondition condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupService/SearchList", ReplyAction="http://tempuri.org/IGroupService/SearchListResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.NTB_GROUP>> SearchListAsync(Wow.Tv.Middle.Model.Db49.wowtv.Group.GroupCondition condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupService/GetAt", ReplyAction="http://tempuri.org/IGroupService/GetAtResponse")]
        Wow.Tv.Middle.Model.Db49.wowtv.NTB_GROUP GetAt(int groupSeq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupService/GetAt", ReplyAction="http://tempuri.org/IGroupService/GetAtResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.NTB_GROUP> GetAtAsync(int groupSeq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupService/Save", ReplyAction="http://tempuri.org/IGroupService/SaveResponse")]
        int Save(Wow.Tv.Middle.Model.Db49.wowtv.NTB_GROUP model, Wow.Tv.Middle.Model.Common.LoginUser loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupService/Save", ReplyAction="http://tempuri.org/IGroupService/SaveResponse")]
        System.Threading.Tasks.Task<int> SaveAsync(Wow.Tv.Middle.Model.Db49.wowtv.NTB_GROUP model, Wow.Tv.Middle.Model.Common.LoginUser loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupService/Delete", ReplyAction="http://tempuri.org/IGroupService/DeleteResponse")]
        void Delete(int groupSeq, Wow.Tv.Middle.Model.Common.LoginUser loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupService/Delete", ReplyAction="http://tempuri.org/IGroupService/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(int groupSeq, Wow.Tv.Middle.Model.Common.LoginUser loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupService/Copy", ReplyAction="http://tempuri.org/IGroupService/CopyResponse")]
        void Copy(int groupSeq, Wow.Tv.Middle.Model.Common.LoginUser loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupService/Copy", ReplyAction="http://tempuri.org/IGroupService/CopyResponse")]
        System.Threading.Tasks.Task CopyAsync(int groupSeq, Wow.Tv.Middle.Model.Common.LoginUser loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupService/B", ReplyAction="http://tempuri.org/IGroupService/BResponse")]
        Wow.Tv.Middle.Model.Db49.wowtv.CCC[] B(int seq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupService/B", ReplyAction="http://tempuri.org/IGroupService/BResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.CCC[]> BAsync(int seq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupService/BB", ReplyAction="http://tempuri.org/IGroupService/BBResponse")]
        Wow.Tv.Middle.Model.Db49.wowtv.CCC BB(int seq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupService/BB", ReplyAction="http://tempuri.org/IGroupService/BBResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.CCC> BBAsync(int seq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupService/BBB", ReplyAction="http://tempuri.org/IGroupService/BBBResponse")]
        Wow.Tv.Middle.Model.Db49.wowtv.AAA BBB(int seq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupService/BBB", ReplyAction="http://tempuri.org/IGroupService/BBBResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.AAA> BBBAsync(int seq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupService/BBBB", ReplyAction="http://tempuri.org/IGroupService/BBBBResponse")]
        Wow.Tv.Middle.Model.Db49.wowtv.Group.My BBBB(int seq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupService/BBBB", ReplyAction="http://tempuri.org/IGroupService/BBBBResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.Group.My> BBBBAsync(int seq);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGroupServiceChannel : Wow.Tv.Admin.GroupService.IGroupService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GroupServiceClient : System.ServiceModel.ClientBase<Wow.Tv.Admin.GroupService.IGroupService>, Wow.Tv.Admin.GroupService.IGroupService {
        
        public GroupServiceClient() {
        }
        
        public GroupServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GroupServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GroupServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GroupServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.NTB_GROUP> SearchList(Wow.Tv.Middle.Model.Db49.wowtv.Group.GroupCondition condition) {
            return base.Channel.SearchList(condition);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.NTB_GROUP>> SearchListAsync(Wow.Tv.Middle.Model.Db49.wowtv.Group.GroupCondition condition) {
            return base.Channel.SearchListAsync(condition);
        }
        
        public Wow.Tv.Middle.Model.Db49.wowtv.NTB_GROUP GetAt(int groupSeq) {
            return base.Channel.GetAt(groupSeq);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.NTB_GROUP> GetAtAsync(int groupSeq) {
            return base.Channel.GetAtAsync(groupSeq);
        }
        
        public int Save(Wow.Tv.Middle.Model.Db49.wowtv.NTB_GROUP model, Wow.Tv.Middle.Model.Common.LoginUser loginUser) {
            return base.Channel.Save(model, loginUser);
        }
        
        public System.Threading.Tasks.Task<int> SaveAsync(Wow.Tv.Middle.Model.Db49.wowtv.NTB_GROUP model, Wow.Tv.Middle.Model.Common.LoginUser loginUser) {
            return base.Channel.SaveAsync(model, loginUser);
        }
        
        public void Delete(int groupSeq, Wow.Tv.Middle.Model.Common.LoginUser loginUser) {
            base.Channel.Delete(groupSeq, loginUser);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(int groupSeq, Wow.Tv.Middle.Model.Common.LoginUser loginUser) {
            return base.Channel.DeleteAsync(groupSeq, loginUser);
        }
        
        public void Copy(int groupSeq, Wow.Tv.Middle.Model.Common.LoginUser loginUser) {
            base.Channel.Copy(groupSeq, loginUser);
        }
        
        public System.Threading.Tasks.Task CopyAsync(int groupSeq, Wow.Tv.Middle.Model.Common.LoginUser loginUser) {
            return base.Channel.CopyAsync(groupSeq, loginUser);
        }
        
        public Wow.Tv.Middle.Model.Db49.wowtv.CCC[] B(int seq) {
            return base.Channel.B(seq);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.CCC[]> BAsync(int seq) {
            return base.Channel.BAsync(seq);
        }
        
        public Wow.Tv.Middle.Model.Db49.wowtv.CCC BB(int seq) {
            return base.Channel.BB(seq);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.CCC> BBAsync(int seq) {
            return base.Channel.BBAsync(seq);
        }
        
        public Wow.Tv.Middle.Model.Db49.wowtv.AAA BBB(int seq) {
            return base.Channel.BBB(seq);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.AAA> BBBAsync(int seq) {
            return base.Channel.BBBAsync(seq);
        }
        
        public Wow.Tv.Middle.Model.Db49.wowtv.Group.My BBBB(int seq) {
            return base.Channel.BBBB(seq);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.Group.My> BBBBAsync(int seq) {
            return base.Channel.BBBBAsync(seq);
        }
    }
}
