//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Admin.RegCateManageService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RegCateManageService.IRegCateManageService")]
    public interface IRegCateManageService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegCateManageService/YearIncomeList", ReplyAction="http://tempuri.org/IRegCateManageService/YearIncomeListResponse")]
        Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.YearIncome[] YearIncomeList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegCateManageService/YearIncomeList", ReplyAction="http://tempuri.org/IRegCateManageService/YearIncomeListResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.YearIncome[]> YearIncomeListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegCateManageService/YearIncomeSave", ReplyAction="http://tempuri.org/IRegCateManageService/YearIncomeSaveResponse")]
        Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.YearIncomeModifyResult[] YearIncomeSave(Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.YearIncome[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegCateManageService/YearIncomeSave", ReplyAction="http://tempuri.org/IRegCateManageService/YearIncomeSaveResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.YearIncomeModifyResult[]> YearIncomeSaveAsync(Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.YearIncome[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegCateManageService/IvstFavorObjList", ReplyAction="http://tempuri.org/IRegCateManageService/IvstFavorObjListResponse")]
        Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.IvstFavorObj[] IvstFavorObjList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegCateManageService/IvstFavorObjList", ReplyAction="http://tempuri.org/IRegCateManageService/IvstFavorObjListResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.IvstFavorObj[]> IvstFavorObjListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegCateManageService/IvstFavorObjSave", ReplyAction="http://tempuri.org/IRegCateManageService/IvstFavorObjSaveResponse")]
        Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.IvstFavorObjModifyResult[] IvstFavorObjSave(Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.IvstFavorObj[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegCateManageService/IvstFavorObjSave", ReplyAction="http://tempuri.org/IRegCateManageService/IvstFavorObjSaveResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.IvstFavorObjModifyResult[]> IvstFavorObjSaveAsync(Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.IvstFavorObj[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegCateManageService/OrgnInfoAcquirerList", ReplyAction="http://tempuri.org/IRegCateManageService/OrgnInfoAcquirerListResponse")]
        Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.OrgnInfoAcquirer[] OrgnInfoAcquirerList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegCateManageService/OrgnInfoAcquirerList", ReplyAction="http://tempuri.org/IRegCateManageService/OrgnInfoAcquirerListResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.OrgnInfoAcquirer[]> OrgnInfoAcquirerListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegCateManageService/OrgnInfoAcquirerSave", ReplyAction="http://tempuri.org/IRegCateManageService/OrgnInfoAcquirerSaveResponse")]
        Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.OrgnInfoAcquirerModifyResult[] OrgnInfoAcquirerSave(Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.OrgnInfoAcquirer[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegCateManageService/OrgnInfoAcquirerSave", ReplyAction="http://tempuri.org/IRegCateManageService/OrgnInfoAcquirerSaveResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.OrgnInfoAcquirerModifyResult[]> OrgnInfoAcquirerSaveAsync(Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.OrgnInfoAcquirer[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegCateManageService/IvstProdList", ReplyAction="http://tempuri.org/IRegCateManageService/IvstProdListResponse")]
        Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.IvstProd[] IvstProdList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegCateManageService/IvstProdList", ReplyAction="http://tempuri.org/IRegCateManageService/IvstProdListResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.IvstProd[]> IvstProdListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegCateManageService/IvstProdSave", ReplyAction="http://tempuri.org/IRegCateManageService/IvstProdSaveResponse")]
        Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.IvstProdModifyResult[] IvstProdSave(Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.IvstProd[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegCateManageService/IvstProdSave", ReplyAction="http://tempuri.org/IRegCateManageService/IvstProdSaveResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.IvstProdModifyResult[]> IvstProdSaveAsync(Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.IvstProd[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegCateManageService/InvstTendencyList", ReplyAction="http://tempuri.org/IRegCateManageService/InvstTendencyListResponse")]
        Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.InvstTendency[] InvstTendencyList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegCateManageService/InvstTendencyList", ReplyAction="http://tempuri.org/IRegCateManageService/InvstTendencyListResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.InvstTendency[]> InvstTendencyListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegCateManageService/InvstTendencySave", ReplyAction="http://tempuri.org/IRegCateManageService/InvstTendencySaveResponse")]
        Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.InvstTendencyModifyResult[] InvstTendencySave(Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.InvstTendency[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegCateManageService/InvstTendencySave", ReplyAction="http://tempuri.org/IRegCateManageService/InvstTendencySaveResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.InvstTendencyModifyResult[]> InvstTendencySaveAsync(Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.InvstTendency[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegCateManageService/MainStockTraderList", ReplyAction="http://tempuri.org/IRegCateManageService/MainStockTraderListResponse")]
        Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.MainStockTrader[] MainStockTraderList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegCateManageService/MainStockTraderList", ReplyAction="http://tempuri.org/IRegCateManageService/MainStockTraderListResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.MainStockTrader[]> MainStockTraderListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegCateManageService/MainStockTraderSave", ReplyAction="http://tempuri.org/IRegCateManageService/MainStockTraderSaveResponse")]
        Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.MainStockTraderModifyResult[] MainStockTraderSave(Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.MainStockTrader[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegCateManageService/MainStockTraderSave", ReplyAction="http://tempuri.org/IRegCateManageService/MainStockTraderSaveResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.MainStockTraderModifyResult[]> MainStockTraderSaveAsync(Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.MainStockTrader[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegCateManageService/IvstScaleList", ReplyAction="http://tempuri.org/IRegCateManageService/IvstScaleListResponse")]
        Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.IvstScale[] IvstScaleList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegCateManageService/IvstScaleList", ReplyAction="http://tempuri.org/IRegCateManageService/IvstScaleListResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.IvstScale[]> IvstScaleListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegCateManageService/IvstScaleSave", ReplyAction="http://tempuri.org/IRegCateManageService/IvstScaleSaveResponse")]
        Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.IvstScaleModifyResult[] IvstScaleSave(Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.IvstScale[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegCateManageService/IvstScaleSave", ReplyAction="http://tempuri.org/IRegCateManageService/IvstScaleSaveResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.IvstScaleModifyResult[]> IvstScaleSaveAsync(Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.IvstScale[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegCateManageService/FavorFieldList", ReplyAction="http://tempuri.org/IRegCateManageService/FavorFieldListResponse")]
        Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.FavorField[] FavorFieldList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegCateManageService/FavorFieldList", ReplyAction="http://tempuri.org/IRegCateManageService/FavorFieldListResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.FavorField[]> FavorFieldListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegCateManageService/FavorFieldSave", ReplyAction="http://tempuri.org/IRegCateManageService/FavorFieldSaveResponse")]
        Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.FavorFieldModifyResult[] FavorFieldSave(Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.FavorField[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegCateManageService/FavorFieldSave", ReplyAction="http://tempuri.org/IRegCateManageService/FavorFieldSaveResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.FavorFieldModifyResult[]> FavorFieldSaveAsync(Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.FavorField[] list);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRegCateManageServiceChannel : Wow.Tv.Admin.RegCateManageService.IRegCateManageService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RegCateManageServiceClient : System.ServiceModel.ClientBase<Wow.Tv.Admin.RegCateManageService.IRegCateManageService>, Wow.Tv.Admin.RegCateManageService.IRegCateManageService {
        
        public RegCateManageServiceClient() {
        }
        
        public RegCateManageServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RegCateManageServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegCateManageServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegCateManageServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.YearIncome[] YearIncomeList() {
            return base.Channel.YearIncomeList();
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.YearIncome[]> YearIncomeListAsync() {
            return base.Channel.YearIncomeListAsync();
        }
        
        public Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.YearIncomeModifyResult[] YearIncomeSave(Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.YearIncome[] list) {
            return base.Channel.YearIncomeSave(list);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.YearIncomeModifyResult[]> YearIncomeSaveAsync(Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.YearIncome[] list) {
            return base.Channel.YearIncomeSaveAsync(list);
        }
        
        public Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.IvstFavorObj[] IvstFavorObjList() {
            return base.Channel.IvstFavorObjList();
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.IvstFavorObj[]> IvstFavorObjListAsync() {
            return base.Channel.IvstFavorObjListAsync();
        }
        
        public Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.IvstFavorObjModifyResult[] IvstFavorObjSave(Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.IvstFavorObj[] list) {
            return base.Channel.IvstFavorObjSave(list);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.IvstFavorObjModifyResult[]> IvstFavorObjSaveAsync(Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.IvstFavorObj[] list) {
            return base.Channel.IvstFavorObjSaveAsync(list);
        }
        
        public Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.OrgnInfoAcquirer[] OrgnInfoAcquirerList() {
            return base.Channel.OrgnInfoAcquirerList();
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.OrgnInfoAcquirer[]> OrgnInfoAcquirerListAsync() {
            return base.Channel.OrgnInfoAcquirerListAsync();
        }
        
        public Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.OrgnInfoAcquirerModifyResult[] OrgnInfoAcquirerSave(Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.OrgnInfoAcquirer[] list) {
            return base.Channel.OrgnInfoAcquirerSave(list);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.OrgnInfoAcquirerModifyResult[]> OrgnInfoAcquirerSaveAsync(Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.OrgnInfoAcquirer[] list) {
            return base.Channel.OrgnInfoAcquirerSaveAsync(list);
        }
        
        public Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.IvstProd[] IvstProdList() {
            return base.Channel.IvstProdList();
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.IvstProd[]> IvstProdListAsync() {
            return base.Channel.IvstProdListAsync();
        }
        
        public Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.IvstProdModifyResult[] IvstProdSave(Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.IvstProd[] list) {
            return base.Channel.IvstProdSave(list);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.IvstProdModifyResult[]> IvstProdSaveAsync(Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.IvstProd[] list) {
            return base.Channel.IvstProdSaveAsync(list);
        }
        
        public Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.InvstTendency[] InvstTendencyList() {
            return base.Channel.InvstTendencyList();
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.InvstTendency[]> InvstTendencyListAsync() {
            return base.Channel.InvstTendencyListAsync();
        }
        
        public Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.InvstTendencyModifyResult[] InvstTendencySave(Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.InvstTendency[] list) {
            return base.Channel.InvstTendencySave(list);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.InvstTendencyModifyResult[]> InvstTendencySaveAsync(Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.InvstTendency[] list) {
            return base.Channel.InvstTendencySaveAsync(list);
        }
        
        public Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.MainStockTrader[] MainStockTraderList() {
            return base.Channel.MainStockTraderList();
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.MainStockTrader[]> MainStockTraderListAsync() {
            return base.Channel.MainStockTraderListAsync();
        }
        
        public Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.MainStockTraderModifyResult[] MainStockTraderSave(Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.MainStockTrader[] list) {
            return base.Channel.MainStockTraderSave(list);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.MainStockTraderModifyResult[]> MainStockTraderSaveAsync(Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.MainStockTrader[] list) {
            return base.Channel.MainStockTraderSaveAsync(list);
        }
        
        public Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.IvstScale[] IvstScaleList() {
            return base.Channel.IvstScaleList();
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.IvstScale[]> IvstScaleListAsync() {
            return base.Channel.IvstScaleListAsync();
        }
        
        public Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.IvstScaleModifyResult[] IvstScaleSave(Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.IvstScale[] list) {
            return base.Channel.IvstScaleSave(list);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.IvstScaleModifyResult[]> IvstScaleSaveAsync(Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.IvstScale[] list) {
            return base.Channel.IvstScaleSaveAsync(list);
        }
        
        public Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.FavorField[] FavorFieldList() {
            return base.Channel.FavorFieldList();
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.FavorField[]> FavorFieldListAsync() {
            return base.Channel.FavorFieldListAsync();
        }
        
        public Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.FavorFieldModifyResult[] FavorFieldSave(Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.FavorField[] list) {
            return base.Channel.FavorFieldSave(list);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.FavorFieldModifyResult[]> FavorFieldSaveAsync(Wow.Tv.Middle.Model.Db89.wowbill.RegiCategoryManage.FavorField[] list) {
            return base.Channel.FavorFieldSaveAsync(list);
        }
    }
}
