//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Admin.AdminService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SetPasswordResult", Namespace="http://schemas.datacontract.org/2004/07/Wow.Tv.Middle.Biz.Member")]
    [System.SerializableAttribute()]
    public partial class SetPasswordResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReturnMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TempPasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MobileNo {
            get {
                return this.MobileNoField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileNoField, value) != true)) {
                    this.MobileNoField = value;
                    this.RaisePropertyChanged("MobileNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReturnMessage {
            get {
                return this.ReturnMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ReturnMessageField, value) != true)) {
                    this.ReturnMessageField = value;
                    this.RaisePropertyChanged("ReturnMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TempPassword {
            get {
                return this.TempPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.TempPasswordField, value) != true)) {
                    this.TempPasswordField = value;
                    this.RaisePropertyChanged("TempPassword");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AdminService.IAdminService")]
    public interface IAdminService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/SmsSend", ReplyAction="http://tempuri.org/IAdminService/SmsSendResponse")]
        void SmsSend(string adminId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/SmsSend", ReplyAction="http://tempuri.org/IAdminService/SmsSendResponse")]
        System.Threading.Tasks.Task SmsSendAsync(string adminId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/GetAt", ReplyAction="http://tempuri.org/IAdminService/GetAtResponse")]
        Wow.Tv.Middle.Model.Db49.wowtv.TAB_CMS_ADMIN GetAt(int seq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/GetAt", ReplyAction="http://tempuri.org/IAdminService/GetAtResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.TAB_CMS_ADMIN> GetAtAsync(int seq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/GetAtById", ReplyAction="http://tempuri.org/IAdminService/GetAtByIdResponse")]
        Wow.Tv.Middle.Model.Db49.wowtv.TAB_CMS_ADMIN GetAtById(string adminId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/GetAtById", ReplyAction="http://tempuri.org/IAdminService/GetAtByIdResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.TAB_CMS_ADMIN> GetAtByIdAsync(string adminId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/LoginCheck", ReplyAction="http://tempuri.org/IAdminService/LoginCheckResponse")]
        Wow.Tv.Middle.Model.Db49.wowtv.TAB_CMS_ADMIN LoginCheck(string adminId, string pwd, string mobileAuthNumber, string ip);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/LoginCheck", ReplyAction="http://tempuri.org/IAdminService/LoginCheckResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.TAB_CMS_ADMIN> LoginCheckAsync(string adminId, string pwd, string mobileAuthNumber, string ip);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/GetAdminGroup", ReplyAction="http://tempuri.org/IAdminService/GetAdminGroupResponse")]
        Wow.Tv.Middle.Model.Db49.wowtv.NTB_MENU_GROUP[] GetAdminGroup(int adminSeq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/GetAdminGroup", ReplyAction="http://tempuri.org/IAdminService/GetAdminGroupResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.NTB_MENU_GROUP[]> GetAdminGroupAsync(int adminSeq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/Save", ReplyAction="http://tempuri.org/IAdminService/SaveResponse")]
        int Save(Wow.Tv.Middle.Model.Db49.wowtv.TAB_CMS_ADMIN model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/Save", ReplyAction="http://tempuri.org/IAdminService/SaveResponse")]
        System.Threading.Tasks.Task<int> SaveAsync(Wow.Tv.Middle.Model.Db49.wowtv.TAB_CMS_ADMIN model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/PasswordChange", ReplyAction="http://tempuri.org/IAdminService/PasswordChangeResponse")]
        void PasswordChange(int adminSeq, string currentPassword, string changePassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/PasswordChange", ReplyAction="http://tempuri.org/IAdminService/PasswordChangeResponse")]
        System.Threading.Tasks.Task PasswordChangeAsync(int adminSeq, string currentPassword, string changePassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/SearchList", ReplyAction="http://tempuri.org/IAdminService/SearchListResponse")]
        Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.TAB_CMS_ADMIN> SearchList(Wow.Tv.Middle.Model.Db49.wowtv.Admin.AdminCondition condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/SearchList", ReplyAction="http://tempuri.org/IAdminService/SearchListResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.TAB_CMS_ADMIN>> SearchListAsync(Wow.Tv.Middle.Model.Db49.wowtv.Admin.AdminCondition condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/Delete", ReplyAction="http://tempuri.org/IAdminService/DeleteResponse")]
        void Delete(int seq, Wow.Tv.Middle.Model.Common.LoginUser loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/Delete", ReplyAction="http://tempuri.org/IAdminService/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(int seq, Wow.Tv.Middle.Model.Common.LoginUser loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/DeleteList", ReplyAction="http://tempuri.org/IAdminService/DeleteListResponse")]
        void DeleteList(int[] seqList, Wow.Tv.Middle.Model.Common.LoginUser loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/DeleteList", ReplyAction="http://tempuri.org/IAdminService/DeleteListResponse")]
        System.Threading.Tasks.Task DeleteListAsync(int[] seqList, Wow.Tv.Middle.Model.Common.LoginUser loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/ExcelExport", ReplyAction="http://tempuri.org/IAdminService/ExcelExportResponse")]
        System.IO.MemoryStream ExcelExport(Wow.Tv.Middle.Model.Db49.wowtv.Admin.AdminCondition condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/ExcelExport", ReplyAction="http://tempuri.org/IAdminService/ExcelExportResponse")]
        System.Threading.Tasks.Task<System.IO.MemoryStream> ExcelExportAsync(Wow.Tv.Middle.Model.Db49.wowtv.Admin.AdminCondition condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/usp_AdminCmsPwdInitialize", ReplyAction="http://tempuri.org/IAdminService/usp_AdminCmsPwdInitializeResponse")]
        void usp_AdminCmsPwdInitialize(string adminid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/usp_AdminCmsPwdInitialize", ReplyAction="http://tempuri.org/IAdminService/usp_AdminCmsPwdInitializeResponse")]
        System.Threading.Tasks.Task usp_AdminCmsPwdInitializeAsync(string adminid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/AdminCmsPwdInitializeRanNum", ReplyAction="http://tempuri.org/IAdminService/AdminCmsPwdInitializeRanNumResponse")]
        Wow.Tv.Admin.AdminService.SetPasswordResult AdminCmsPwdInitializeRanNum(string adminId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/AdminCmsPwdInitializeRanNum", ReplyAction="http://tempuri.org/IAdminService/AdminCmsPwdInitializeRanNumResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Admin.AdminService.SetPasswordResult> AdminCmsPwdInitializeRanNumAsync(string adminId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdminServiceChannel : Wow.Tv.Admin.AdminService.IAdminService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdminServiceClient : System.ServiceModel.ClientBase<Wow.Tv.Admin.AdminService.IAdminService>, Wow.Tv.Admin.AdminService.IAdminService {
        
        public AdminServiceClient() {
        }
        
        public AdminServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdminServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SmsSend(string adminId) {
            base.Channel.SmsSend(adminId);
        }
        
        public System.Threading.Tasks.Task SmsSendAsync(string adminId) {
            return base.Channel.SmsSendAsync(adminId);
        }
        
        public Wow.Tv.Middle.Model.Db49.wowtv.TAB_CMS_ADMIN GetAt(int seq) {
            return base.Channel.GetAt(seq);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.TAB_CMS_ADMIN> GetAtAsync(int seq) {
            return base.Channel.GetAtAsync(seq);
        }
        
        public Wow.Tv.Middle.Model.Db49.wowtv.TAB_CMS_ADMIN GetAtById(string adminId) {
            return base.Channel.GetAtById(adminId);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.TAB_CMS_ADMIN> GetAtByIdAsync(string adminId) {
            return base.Channel.GetAtByIdAsync(adminId);
        }
        
        public Wow.Tv.Middle.Model.Db49.wowtv.TAB_CMS_ADMIN LoginCheck(string adminId, string pwd, string mobileAuthNumber, string ip) {
            return base.Channel.LoginCheck(adminId, pwd, mobileAuthNumber, ip);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.TAB_CMS_ADMIN> LoginCheckAsync(string adminId, string pwd, string mobileAuthNumber, string ip) {
            return base.Channel.LoginCheckAsync(adminId, pwd, mobileAuthNumber, ip);
        }
        
        public Wow.Tv.Middle.Model.Db49.wowtv.NTB_MENU_GROUP[] GetAdminGroup(int adminSeq) {
            return base.Channel.GetAdminGroup(adminSeq);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.NTB_MENU_GROUP[]> GetAdminGroupAsync(int adminSeq) {
            return base.Channel.GetAdminGroupAsync(adminSeq);
        }
        
        public int Save(Wow.Tv.Middle.Model.Db49.wowtv.TAB_CMS_ADMIN model) {
            return base.Channel.Save(model);
        }
        
        public System.Threading.Tasks.Task<int> SaveAsync(Wow.Tv.Middle.Model.Db49.wowtv.TAB_CMS_ADMIN model) {
            return base.Channel.SaveAsync(model);
        }
        
        public void PasswordChange(int adminSeq, string currentPassword, string changePassword) {
            base.Channel.PasswordChange(adminSeq, currentPassword, changePassword);
        }
        
        public System.Threading.Tasks.Task PasswordChangeAsync(int adminSeq, string currentPassword, string changePassword) {
            return base.Channel.PasswordChangeAsync(adminSeq, currentPassword, changePassword);
        }
        
        public Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.TAB_CMS_ADMIN> SearchList(Wow.Tv.Middle.Model.Db49.wowtv.Admin.AdminCondition condition) {
            return base.Channel.SearchList(condition);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.TAB_CMS_ADMIN>> SearchListAsync(Wow.Tv.Middle.Model.Db49.wowtv.Admin.AdminCondition condition) {
            return base.Channel.SearchListAsync(condition);
        }
        
        public void Delete(int seq, Wow.Tv.Middle.Model.Common.LoginUser loginUser) {
            base.Channel.Delete(seq, loginUser);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(int seq, Wow.Tv.Middle.Model.Common.LoginUser loginUser) {
            return base.Channel.DeleteAsync(seq, loginUser);
        }
        
        public void DeleteList(int[] seqList, Wow.Tv.Middle.Model.Common.LoginUser loginUser) {
            base.Channel.DeleteList(seqList, loginUser);
        }
        
        public System.Threading.Tasks.Task DeleteListAsync(int[] seqList, Wow.Tv.Middle.Model.Common.LoginUser loginUser) {
            return base.Channel.DeleteListAsync(seqList, loginUser);
        }
        
        public System.IO.MemoryStream ExcelExport(Wow.Tv.Middle.Model.Db49.wowtv.Admin.AdminCondition condition) {
            return base.Channel.ExcelExport(condition);
        }
        
        public System.Threading.Tasks.Task<System.IO.MemoryStream> ExcelExportAsync(Wow.Tv.Middle.Model.Db49.wowtv.Admin.AdminCondition condition) {
            return base.Channel.ExcelExportAsync(condition);
        }
        
        public void usp_AdminCmsPwdInitialize(string adminid) {
            base.Channel.usp_AdminCmsPwdInitialize(adminid);
        }
        
        public System.Threading.Tasks.Task usp_AdminCmsPwdInitializeAsync(string adminid) {
            return base.Channel.usp_AdminCmsPwdInitializeAsync(adminid);
        }
        
        public Wow.Tv.Admin.AdminService.SetPasswordResult AdminCmsPwdInitializeRanNum(string adminId) {
            return base.Channel.AdminCmsPwdInitializeRanNum(adminId);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Admin.AdminService.SetPasswordResult> AdminCmsPwdInitializeRanNumAsync(string adminId) {
            return base.Channel.AdminCmsPwdInitializeRanNumAsync(adminId);
        }
    }
}
