//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.Admin.IRClubService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IRClubService.IIRClubService")]
    public interface IIRClubService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIRClubService/GetList", ReplyAction="http://tempuri.org/IIRClubService/GetListResponse")]
        Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wownet.TAB_IR_CLUB_2010> GetList(Wow.Tv.Middle.Model.Db49.wownet.IRClub.IRClubCondition condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIRClubService/GetList", ReplyAction="http://tempuri.org/IIRClubService/GetListResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wownet.TAB_IR_CLUB_2010>> GetListAsync(Wow.Tv.Middle.Model.Db49.wownet.IRClub.IRClubCondition condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIRClubService/Save", ReplyAction="http://tempuri.org/IIRClubService/SaveResponse")]
        int Save(Wow.Tv.Middle.Model.Db49.wownet.TAB_IR_CLUB_2010 model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIRClubService/Save", ReplyAction="http://tempuri.org/IIRClubService/SaveResponse")]
        System.Threading.Tasks.Task<int> SaveAsync(Wow.Tv.Middle.Model.Db49.wownet.TAB_IR_CLUB_2010 model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIRClubService/Delete", ReplyAction="http://tempuri.org/IIRClubService/DeleteResponse")]
        void Delete(int[] deleteList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIRClubService/Delete", ReplyAction="http://tempuri.org/IIRClubService/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(int[] deleteList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIRClubService/GetData", ReplyAction="http://tempuri.org/IIRClubService/GetDataResponse")]
        Wow.Tv.Middle.Model.Db49.wownet.TAB_IR_CLUB_2010 GetData(int seq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIRClubService/GetData", ReplyAction="http://tempuri.org/IIRClubService/GetDataResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wownet.TAB_IR_CLUB_2010> GetDataAsync(int seq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIRClubService/GetStockCode", ReplyAction="http://tempuri.org/IIRClubService/GetStockCodeResponse")]
        Wow.Tv.Middle.Model.Db22.stock.view_AllStockCode[] GetStockCode(string searchText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIRClubService/GetStockCode", ReplyAction="http://tempuri.org/IIRClubService/GetStockCodeResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db22.stock.view_AllStockCode[]> GetStockCodeAsync(string searchText);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IIRClubServiceChannel : Wow.Tv.Admin.IRClubService.IIRClubService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IRClubServiceClient : System.ServiceModel.ClientBase<Wow.Tv.Admin.IRClubService.IIRClubService>, Wow.Tv.Admin.IRClubService.IIRClubService {
        
        public IRClubServiceClient() {
        }
        
        public IRClubServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IRClubServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IRClubServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IRClubServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wownet.TAB_IR_CLUB_2010> GetList(Wow.Tv.Middle.Model.Db49.wownet.IRClub.IRClubCondition condition) {
            return base.Channel.GetList(condition);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wownet.TAB_IR_CLUB_2010>> GetListAsync(Wow.Tv.Middle.Model.Db49.wownet.IRClub.IRClubCondition condition) {
            return base.Channel.GetListAsync(condition);
        }
        
        public int Save(Wow.Tv.Middle.Model.Db49.wownet.TAB_IR_CLUB_2010 model) {
            return base.Channel.Save(model);
        }
        
        public System.Threading.Tasks.Task<int> SaveAsync(Wow.Tv.Middle.Model.Db49.wownet.TAB_IR_CLUB_2010 model) {
            return base.Channel.SaveAsync(model);
        }
        
        public void Delete(int[] deleteList) {
            base.Channel.Delete(deleteList);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(int[] deleteList) {
            return base.Channel.DeleteAsync(deleteList);
        }
        
        public Wow.Tv.Middle.Model.Db49.wownet.TAB_IR_CLUB_2010 GetData(int seq) {
            return base.Channel.GetData(seq);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wownet.TAB_IR_CLUB_2010> GetDataAsync(int seq) {
            return base.Channel.GetDataAsync(seq);
        }
        
        public Wow.Tv.Middle.Model.Db22.stock.view_AllStockCode[] GetStockCode(string searchText) {
            return base.Channel.GetStockCode(searchText);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db22.stock.view_AllStockCode[]> GetStockCodeAsync(string searchText) {
            return base.Channel.GetStockCodeAsync(searchText);
        }
    }
}
